### ISSUE TITLE
org.pitest.util.PitError: Coverage generation minion exited abnormally

### ISSUE THREAD

**Issue by valentinacupac** [hcoles/pitest#1011]
The following are my plugins

`plugins {
    id 'org.springframework.boot' version '2.6.6'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'info.solidsoft.pitest' version '1.7.4'
}`

I then try to run

`gradle pitest`

I get the error

`> Task :pitest
5:48:41 PM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
5:48:42 PM PIT >> INFO : Incremental analysis reduced number of mutations by 0
5:48:42 PM PIT >> INFO : Created  18 mutation test units in pre scan
5:48:43 PM PIT >> INFO : Sending 56 test classes to minion
5:48:43 PM PIT >> INFO : Sent tests to minion
5:48:43 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR       
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue   
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 17.0.2+8-86
Uptime : 5081
Input ->
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 17.0.2+8-86
Uptime : 5082
Input ->
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:106)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:52)
        at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:149)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:139)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:123)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:54)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 17.0.2+8-86
Uptime : 5081
Input ->
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false

        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:148)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:90)
        ... 7 more

> Task :pitest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pitest'.
> Process 'command 'C:\Users\Valentina.Cupac\.jdks\openjdk-17.0.2\bin\java.exe'' finished with non-zero exit value 1
`

**Comment by valentinacupac** [comment]
Note: This error is manifested only when configuring in build.gradle and running from the command line.

However, if I use the IntelliJ plugin for PIT, the plugin runs normally.

**Comment by hcoles** [comment]
If you can provide a complete, minimal executatable example, I can take a look.

**Comment by hcoles** [comment]
Assuming this relates to this project

https://github.com/valentinacupac/banking-kata-java

The issue is that you are using junit5, but have not configured the pitest junit5 plugin.

As per the documentation at https://gradle-pitest-plugin.solidsoft.info/ you can configure it with

```
pitest {
    pitestVersion = '1.7.5'
    junit5PluginVersion = '0.15'   
}
```

**Comment by szpak** [comment]
@hcoles I improved the error message some time ago - https://github.com/hcoles/pitest/pull/745. Do you know why it is not displayed any longer?

**Comment by hcoles** [comment]
@szpak thanks, I'll take a look tomorrow and see what I've broken.

**Comment by valentinacupac** [comment]
@hcoles yes, that's the project, I've now updated the config as per above, it works now. Thanks!
