### ISSUE TITLE
Gradle pitest failing on 1.9.0

### ISSUE THREAD

**Issue by andre-iasi-moura** [hcoles/pitest#1044]
This is what comes:

VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 17-ea+17-1401
Uptime : 953
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:106)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:52)
        at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:148)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:138)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:124)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:54)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

I am using the 1.7.4 gradle plugin. It works for version 1.8.1

**Comment by hcoles** [comment]
Thanks for the report. If you can put together a minimal project that reproduces the issue, I can take a look.

**Comment by themoffster** [comment]
Here's an example project: https://github.com/themoffster/pitest-example

**Comment by hcoles** [comment]
Thanks @themoffster 

The issue looks to be that, for some reason, the project is not picking up the 1.0.0 release of the pitest juni5 5 test plugin.


`11:18:37 PIT >> FINE : MINION : java.lang.AbstractMethodError: Receiver class org.pitest.junit5.JUnit5TestUnitFinder does not define or inherit an implementation of the resolved method 'abstract java.util.List findTestUnits(java.lang.Class)' of interface org.pitest.testapi.TestUnitFinder.`

@szpak is probably better able to see why that is than I am.

**Comment by themoffster** [comment]
I required this in the pitest config too `pitestVersion = '1.9.0'`

```
pitest {
	mutationThreshold = 100
	coverageThreshold = 100
	outputFormats = ['HTML', 'XML']
	targetClasses = ['**.*Utils']
	targetTests = ['**.*Test']
	timestampedReports = false
//	testPlugin = 'junit5'
	junit5PluginVersion = '1.0.0'
	pitestVersion = '1.9.0'
}
```

**Comment by andre-iasi-moura** [comment]
> As noted in the [release notes for 1.7.4](https://github.com/szpak/gradle-pitest-plugin/releases/tag/release%2F1.7.4):
> 
> > The testPlugin configuration parameter is deprecated and should not be used. In fact, starting with 1.6.7 it is no longer used (it is enough to add the PIT plugin as a buildscript dependency or just set junit5PluginVersion to use the JUnit 5 plugin). In addition, that property is planned to be removed in PIT 1.8.0.
> 
> You should remove `testPlugin = 'junit5'` from your pitest configuration and add `junit5PluginVersion = 1.0.0` instead. `pitest 'org.pitest:pitest-junit5-plugin:1.0.0'` is also not needed then.
> 
> Nevertheless, you could [report](https://github.com/szpak/gradle-pitest-plugin/issues/new) a separate feature request in the plugin project to try to detect the fact that someone manually add `pitest 'org.pitest:pitest-junit5-plugin:1.0.0'`. I'm not sure when it is evaluated, but maybe it would be possible, to detect a situation when GPP overrides a version added by a developer.

That resolved the issue for me. Thanks very much!

**Comment by hcoles** [comment]
@andre-iasi-moura I believe this issue is resolved and can be closed?
