### ISSUE TITLE
Intermittent deadlocks in MutationCoverageReport process

### ISSUE THREAD

**Issue by davidburstrom** [hcoles/pitest#1047]
Spuriously, the MutationCoverageReport process is deadlocking waiting for the minions to die, but there are no minion processes alive according to `jps`. It's as if there is some signalling that gets randomly dropped, maybe due to a concurrency issue.

I've seen this across various versions of Pitest, most recently version 1.9.0, run through Gradle plugin info.solidsoft.pitest:1.7.4. This happens both on Mac and Windows.

```
"pool-1-thread-3" #17 prio=5 os_prio=31 tid=0x000000015998e800 nid=0x5807 waiting on condition [0x0000000178412000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000673fa2310> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:59)
	at org.pitest.mutationtest.execute.MutationTestProcess.waitToDie(MutationTestProcess.java:46)
	at org.pitest.mutationtest.build.MutationTestUnit.waitForMinionToDie(MutationTestUnit.java:92)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestInSeperateProcessForMutationRange(MutationTestUnit.java:85)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestsInSeperateProcess(MutationTestUnit.java:68)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:55)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hcoles** [comment]
@davidburstrom Thanks for the report. 

I've (unsurprisngly) not been able to reproduce this, so a fix is going to be difficult (not helped by the fact that the code in this area is old and deeply unpleasant).

Are any of the minion processes left alive when this occurs? Or is only the main process still running?

**Comment by hcoles** [comment]
@davidburstrom If you set `verbose=true` pitest will spit out a lot more info.

**Comment by hcoles** [comment]
@davidburstrom I've just release pitest 1.9.1, this contains a small change to test the theory that the hangs are caused by the final 'done' signal from the minion getting lost.

Could try this out once it's synced through and report back on whether the hangs still occur?

**Comment by davidburstrom** [comment]
I can try that out! Will that require `verbose=true` to detect, or will it be obvious from the context?

**Comment by hcoles** [comment]
@davidburstrom The change just resends the signal a few times. So, if the issue is that it's getting lost it should eliminate the problem (or at least reduce the frequency with which it happens).

If the volume of output doesn't cause you any problems, enabling verbose would still be good. If you do get another hang, it might give a bit more info to work from.

**Comment by davidburstrom** [comment]
If you ask me, I'd say failing fast is the better option, instead of assuming responsibility to stabilize wrt the environment.

**Comment by hcoles** [comment]
Which is happily also the easiest option.

**Comment by hcoles** [comment]
@davidburstrom 
Releasing a fix for this now as pitest 1.9.2. Instead of hangs you should now receive errors.

**Comment by davidburstrom** [comment]
Cool, I'm trying it out now!

**Comment by hcoles** [comment]
Actually, my description of the behaviour is not quite right. If the coverage process pitest runs first dies, you'll get a fast error. If the process doesn't start/dies during the mutation testing phase you'll see run errors reported against each mutation.

The first scenario was easy to reproduce for a test. The second is not so easy (without first causing it at the coverage stage).

**Comment by davidburstrom** [comment]
I can confirm that I came across the fail-fast, as in `Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally! (MINION_DIED)`.

**Comment by davidburstrom** [comment]
Regarding the overarching stability question, I notice that the various spawned Pitest processes (MutationCoverageReport, CoverageMinion, MutationTestMinion) are started with default memory allowances, which on my machine means allocating 1GB up front, which is far more than necessary. Depending on the number of threads, this means e.g. 5 GB per execution.

Since I'm using the Gradle plugin, I've tried experimenting with setting
```
mainProcessJvmArgs.add("-Xmx100m")
childProcessJvmArgs.add("-Xmx100m")
```
but these aren't respected. I see that neither the MutationCoverageReport nor CoverageMinion 

I'd say it's necessary to support custom memory settings in order to stabilize execution locally and in CI.
