### ISSUE TITLE
Comma separated excludedGroups in surefire plugin configuration

### ISSUE THREAD

**Issue by johnathana** [hcoles/pitest#1238]
Comma separated `excludedGroups` in surefure plugin configuration is not parsed correctly. A sample configuration: 
https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#filtering-by-tags

```
<build>
    <plugins>
        ...
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>3.1.2</version>
            <configuration>
                <excludedGroups>integration, regression</excludedGroups>
            </configuration>
        </plugin>
    </plugins>
</build>
```
`org.pitest.maven.SurefireConfigConverter#extractStrings` will parse it as `["integration,",  "regression"]` (mind the comma as last character), causing the following exception:

```
2:47:29 PM PIT >> INFO : MINION : 2:47:29 PM PIT >> INFO : Checking environment
2:47:31 PM PIT >> FINE : MINION : java.lang.IllegalArgumentException: Error creating tag filter
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.junit5.JUnit5TestUnitFinder.findTestUnits(JUnit5TestUnitFinder.java:78)
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:20)
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:64)
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:47)
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:36)
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:165)
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:151)
2:47:31 PM PIT >> FINE : MINION :       at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:82)
2:47:31 PM PIT >> FINE : MINION : Caused by: org.junit.platform.commons.PreconditionViolationException: Tag name [integration,] must be syntactically valid
```

**Comment by hcoles** [comment]
Closing at #1239 was released in 1.14.3
