### ISSUE TITLE
Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.

### ISSUE THREAD

**Issue by Jeno1352** [hcoles/pitest#1277]
I have a Junit test and when I am trying to run the mutation testing on it  Using PItest .it's give me this error
INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
 INFO : Incremental analysis reduced number of mutations by 0
 INFO : Created 0 mutation test units in pre scan
Exception in thread "main" org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
See https://pitest.org for more details.
	at org.pitest.mutationtest.tooling.MutationCoverage.checkMutationsFound(MutationCoverage.java:393)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:136)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:129)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:57)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)

**Comment by hcoles** [comment]
The first part of this error message is asking you to enable verbose logging before reporting an issue. Did you do that? If so, what did the log say.

This part

> Exception in thread "main" org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.

Explains that pitest wasn't able to generate a mutations, possible because the supplied class path or filters are incorrect. Have you checked that the classpath is correct and that the filters you are using match your code?

You seem to be using the commandline version of pitest, rather than one of the build integrations as recomended in the documentation. Unless there is a good reason not to, I would suggest switching to the maven/gradle plugin as this is less error prone.

**Comment by hcoles** [comment]
Closing as no response from OP.
