### ISSUE TITLE
org.pitest.util.PitError: null

### ISSUE THREAD

**Issue by caarlos0** [hcoles/pitest#212]
Don't have any idea why, but, here it is:

```
Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 24.76-b04
Uptime : 993762
Input -> 
 1 : -XX:MaxPermSize=512m
 2 : -Xmx2g
 3 : -Dclassworlds.conf=/usr/share/maven3/bin/m2.conf
 4 : -Dmaven.home=/usr/share/maven3
BootClassPathSupported : true

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
	at org.pitest.mutationtest.execute.MutationTestProcess.waitToDie(MutationTestProcess.java:49)
	at org.pitest.mutationtest.build.MutationTestUnit.waitForSlaveToDie(MutationTestUnit.java:80)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestInSeperateProcessForMutationRange(MutationTestUnit.java:72)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestsInSeperateProcess(MutationTestUnit.java:114)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:54)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pitest.util.PitError: null
```

**Comment by hcoles** [comment]
@caarlos0 Can you clone

https://github.com/hcoles/pitest-issue-starter

And run mvn verify on the machine where you encountered this error?

If this runs successfully it rules out some sort of issue with the machine.
