### ISSUE TITLE
PiTest not able to detect all the tests when running through command line

### ISSUE THREAD

**Issue by shivamrana** [hcoles/pitest#234]
When I am running piTest using piTest maven command, it finds 26 test classes and detects 41 tests but if I am using piTest command line utility, though it finds all 26 test classes but it only detects 2 tests in them. I need to use piTest command line for some reason, so please help me with this issue. Below is the output I get while running it from command line: 

```
.................
.................
12:59:06 PM PIT >> INFO : Sending 26 test classes to slave
12:59:06 PM PIT >> INFO : Sent tests to slave
12:59:06 PM PIT >> INFO : SLAVE : 12:59:06 PM PIT >> INFO : Checking environment

12:59:06 PM PIT >> INFO : SLAVE : 12:59:06 PM PIT >> WARNING : Could not load org.devfactory.metrics.filters.RequestFilterTest$1 (NoClassDefFoundError: javax/servlet/FilterChain)

12:59:07 PM PIT >> INFO : SLAVE : RuntimeException while transforming  org/devfactory/metrics/logging/LoggingUtilTest

12:59:07 PM PIT >> INFO : SLAVE : java.lang.UnsupportedOperationException: Tried to retrieve value but had None.

12:59:07 PM PIT >> INFO : SLAVE : 	at org.pitest.functional.Option$None.value(Option.java:96)
12:59:07 PM PIT >> INFO : SLAVE : 
	at org.pitest.classinfo.ComputeClassWriter.typeInfo(ComputeClassWriter.java:186)

12:59:07 PM PIT >> INFO : SLAVE : 	at org.pitest.classinfo.ComputeClassWriter.getCommonSuperClass(ComputeClassWriter.java:69)
	at org.pitest.reloc.asm.ClassWriter.a(Unknown Source)
12:59:07 PM PIT >> INFO : SLAVE : 
	at org.pitest.reloc.asm.Frame.a(Unknown Source)
	at org.pitest.reloc.asm.Frame.a(Unknown Source)
12:59:07 PM PIT >> INFO : SLAVE : 
	at org.pitest.reloc.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.pitest.coverage.analysis.AbstractCoverageStrategy.visitMaxs(AbstractCoverageStrategy.java:71)

12:59:07 PM PIT >> INFO : SLAVE : 	at org.pitest.reloc.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.tree.MethodNode.accept(Unknown Source)
	at org.pitest.coverage.analysis.CoverageAnalyser.visitEnd(CoverageAnalyser.java:63)
	at org.pitest.reloc.asm.ClassReader.b(Unk
12:59:07 PM PIT >> INFO : SLAVE : nown Source)
	at org.pitest.reloc.asm.ClassReader.accept(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.accept(Unknown Source)
	at org.pitest.coverage.CoverageTransformer.transformBytes(CoverageTransformer.java:54)
	at org.pitest.coverage.CoverageTra
12:59:07 PM PIT >> INFO : SLAVE : nsformer.transform(CoverageTransformer.java:35)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method
12:59:07 PM PIT >> INFO : SLAVE : )
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader
12:59:07 PM PIT >> INFO : SLAVE : .java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)

12:59:07 PM PIT >> INFO : SLAVE : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Cl
12:59:07 PM PIT >> INFO : SLAVE : ass.java:348)
	at org.pitest.classinfo.ClassName$2.apply(ClassName.java:107)
	at org.pitest.classinfo.ClassName$2.apply(ClassName.java:102)
	at org.pitest.functional.FCollection.flatMapTo(FCollection.java:56)
	at org.pitest.functional.FCollection.flatMap(F
12:59:07 PM PIT >> INFO : SLAVE : Collection.java:66)
	at org.pitest.coverage.execute.CoverageSlave.discoverTests(CoverageSlave.java:147)
	at org.pitest.coverage.execute.CoverageSlave.getTestsFromParent(CoverageSlave.java:128)
	at org.pitest.coverage.execute.CoverageSlave.main(CoverageSlav
12:59:07 PM PIT >> INFO : SLAVE : e.java:79)

12:59:07 PM PIT >> INFO : SLAVE : 12:59:07 PM PIT >> INFO : Found  2 tests

12:59:07 PM PIT >> INFO : SLAVE : 12:59:07 PM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

12:59:07 PM PIT >> INFO : SLAVE : 12:59:07 PM PIT >> INFO : 2 tests received
....................
....................
```

**Comment by shivamrana** [comment]
I had something wrong in the classpath provided, please ignore.
