### ISSUE TITLE
How to tell which tests are failing

### ISSUE THREAD

**Issue by lbergelson** [hcoles/pitest#250]
I'm trying to run pitest, and I'm seeing `Mutation testing requires a green suite`.  Is there any way to identify which tests are failing?  No report file is written and I don't see it in any of the output.  

I'm running using the gradle plugin.  

Here's my output.  (I did tried running with verbose logging but it wasn't any more illuminating.)

```
5:53:36 PM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
5:53:37 PM PIT >> INFO : SLAVE : objc[43278]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be
5:53:37 PM PIT >> INFO : SLAVE : used. Which one is undefined.

5:53:37 PM PIT >> INFO : Sending 94 test classes to slave
5:53:37 PM PIT >> INFO : Sent tests to slave
5:53:38 PM PIT >> INFO : SLAVE : 5:53:38 PM PIT >> INFO : Found  94 tests

5:53:38 PM PIT >> INFO : SLAVE : 5:53:38 PM PIT >> INFO : Dependency analysis reduced number of potential tests by 0
5:53:38 PM PIT >> INFO : 94 tests received

/- \ | / - \ |  5:53:42 PM PIT >> INFO : SLAVE : 5:53:42 PM PIT >> WARNING : More threads at end of test (8) _ than start. (5)

/- \ | / - \ | / - \ | / - \  5:54:17 PM PIT >> INFO : SLAVE : 2016-02-04 17:54:17 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

5:54:18 PM PIT >> INFO : SLAVE : 2016-02-04 17:54:18 WARN  MetricsConfig:125 - Cannot locate configuration: tried hadoop-metrics2-namenode.properties,hadoop-metrics2.properties

5:54:18 PM PIT >> INFO : SLAVE : 2016-02-04 17:54:18 WARN  HttpRequestLog:100 - Jetty request log can only be enabled using Log4j

5:54:19 PM PIT >> INFO : SLAVE : 2016-02-04 17:54:19 WARN  HttpRequestLog:100 - Jetty request log can only be enabled using Log4j

5:54:21 PM PIT >> INFO : SLAVE : 2016-02-04 17:54:21 WARN  DirectoryScanner:378 - DirectoryScanner: shutdown has been called

5:54:21 PM PIT >> INFO : SLAVE : 2016-02-04 17:54:21 WARN  DataNode:704 - BPOfferService for Block pool BP-1426025286-10.1.4.233-1454626458015 (Datanode Uuid 095d2a55-1170-4182-81a8-41cdec6a476b) service to localhost/127.0.0.1:55962 interrupted

5:54:21 PM PIT >> INFO : SLAVE : 2016-02-04 17:54:21 WARN  DataNode:834 - Ending block pool service for: Block pool BP-1426025286-10.1.4.233-1454626458015 (Datanode Uuid 095d2a55-1170-4182-81a8-41cdec6a476b) service to localhost/127.0.0.1:55962

5:54:21 PM PIT >> INFO : SLAVE : 5:54:21 PM PIT >> WARNING : More threads at end of test (48) _ than start. (8)

|/ - \ | / - \ | / - \ | / -  5:54:24 PM PIT >> INFO : SLAVE : Error: Could not find or load main class

\| / - \ | / - \ | / - \ | / - \ | / - \ |  5:57:18 PM PIT >> WARNING : Description [testClass=org.broadinstitute.hellbender.utils.recalibration.BQSRGathererUnitTest, name=_] did not pass without mutation.
/- \ | / - \ | / - \  5:57:20 PM PIT >> INFO : SLAVE : 5:57:20 PM PIT >> WARNING : More threads at end of test (10) _ than start. (9)

5:57:20 PM PIT >> INFO : SLAVE : Error: For input string: "#:GATKTable:0:0:;"

|/ - \  5:57:20 PM PIT >> INFO : SLAVE : 5:57:20 PM PIT >> WARNING : More threads at end of test (67) _ than start. (10)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMale)

| 5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordFemale)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingGender)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordAffected)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordUnaffected)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection-9)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection0)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelated)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelatedExtraLine)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(explicitTrio)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(implicitTrio)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(partialTrio)
5:57:20 PM PIT >> INFO : SLAVE :

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(bigPedigree)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMale)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordFemale)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(si
5:57:20 PM PIT >> INFO : SLAVE : ngleRecordMissingGender)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordAffected)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordUnaffected)
2016-02-04 17:57:20 WARN  PedReaderUnitTe
5:57:20 PM PIT >> INFO : SLAVE : st:139 - Test TestDataProvider(singleRecordMissingAffection-9)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection0)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelated)
5:57:20 PM PIT >> INFO : SLAVE :
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelatedExtraLine)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(explicitTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(implicitTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(partialTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(bigPedigree)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMale)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordFemale)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingGender)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordAffected)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordUnaffected)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection-9)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection0)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelated)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelatedExtraLine)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(explicitTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(implicitTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(partialTrio)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(bigPedigree)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:225 - Test TestDataProvider(missingFam)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:225 - Test TestDataProvider(missingParents)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:225 - Test TestDataProvider(missingSex)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:225 - Test TestDataProvider(missingPhenotype)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:225 - Test TestDataProvider(missingEverythingButGender)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMale)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordFemale)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingGender)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataPr
5:57:20 PM PIT >> INFO : SLAVE : ovider(singleRecordAffected)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordUnaffected)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection-9)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection0)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelated)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelatedExtraLine)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(explicitTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(implicitTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(partialTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(bigPedigree)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMale)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordFemale)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingGender)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordAffected)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestData
5:57:20 PM PIT >> INFO : SLAVE : Provider(singleRecordUnaffected)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection-9)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection0)
2016-02-04 17:57
5:57:20 PM PIT >> INFO : SLAVE : :20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelated)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelatedExtraLine)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(explicitTrio)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvide
5:57:20 PM PIT >> INFO : SLAVE : r(implicitTrio)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(partialTrio)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(bigPedigree)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMale)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordFemale)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingGender)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordAffected)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordUnaffected)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection-9)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(singleRecordMissingAffection0)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelated)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(multipleUnrelatedExtraLine)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(explicitTrio)
2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(implicitTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(partialTrio)

5:57:20 PM PIT >> INFO : SLAVE : 2016-02-04 17:57:20 WARN  PedReaderUnitTest:139 - Test TestDataProvider(bigPedigree)

/- \ | / - \ | / - \ | / - \ | / -  5:57:21 PM PIT >> INFO : Calculated coverage in 224 seconds.
Exception in thread "main" org.pitest.help.PitHelpError: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
See http://pitest.org for more details.
	at org.pitest.coverage.execute.DefaultCoverageGenerator.verifyBuildSuitableForMutationTesting(DefaultCoverageGenerator.java:106)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:91)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:48)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:118)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:101)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:71)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:43)
:pitest FAILED
```

**Comment by hcoles** [comment]
If you enable verbose logging it should be possible to determine the failing test from the log output.

**Comment by lbergelson** [comment]
So I was running with `gradle pitest --debug --stacktrace` thinking that that would be the maximum verbosity.  I didn't realize that pitest had it's own verbosity parameter.  

For anyone else who runs into this in the future, you can configure verbosity in your build.gradle by adding `verbose = true`

```
pitest {

     ... (your settings here) ...

    verbose = true
}
```

Thanks for the reply.  Sorry for the confusion!

**Comment by ninjubohra** [comment]
Hello,

Having the same issue in that pitest run says `PitHelpError: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.` but all test pass with normal `gradle test` invocation

I added the verbose flag in my build.gradle
```
plugins {
    id 'info.solidsoft.pitest' version '1.3.0'
}

pitest {
    useClasspathFile = true
    timestampedReports = false
    verbose = true
}
```
and I get the following output at the end of the console
```
10:36:58 AM PIT >> INFO : MINION : 10:36:58 AM PIT >> FINE : Gathering coverage for test Description [testClass=com.mastercard.srci.middleware.validator.MerchantCallbackUrlValidatorTest, name=positivePath_CallbackUrlIsEmpty_ShouldReturnMerchantCallbackUrl(com.mastercard.srci.middleware.vali
10:36:58 AM PIT >> INFO : MINION : dator.MerchantCallbackUrlValidatorTest)]

10:36:58 AM PIT >> FINE : MINION : MerchantCallbackUrlValidator.class 2018-11-14 10:36:58,087 INFO[com.mastercard.srci.middleware.validator.MerchantCallbackUrlValidator,THREAD=main,DOMAIN=,DEP_VERSION=,ENVIRONMENT=][CORRELATION_ID=] [MESSAGE=Method invoked ,METHOD_NAME=validateCallbackOverr
10:36:58 AM PIT >> FINE : MINION : ide,METHOD_PARAMETERS=callbackUrl:,merchantCallbackUrl:https://mpass-v7-dev.us-east-2.elasticbeanstalk.com/callback]

10:36:58 AM PIT >> INFO : MINION : 10:36:58 AM PIT >> FINE : Gathering coverage for test Description [testClass=com.mastercard.srci.middleware.validator.MerchantCallbackUrlValidatorTest, name=positivePath_CallbackUrlIsNull_ShouldReturnMerchantCallbackUrl(com.mastercard.srci.middleware.valid
10:36:58 AM PIT >> INFO : MINION : ator.MerchantCallbackUrlValidatorTest)]

10:36:58 AM PIT >> FINE : MINION : MerchantCallbackUrlValidator.class 2018-11-14 10:36:58,088 INFO[com.mastercard.srci.middleware.validator.MerchantCallbackUrlValidator,THREAD=main,DOMAIN=,DEP_VERSION=,ENVIRONMENT=][CORRELATION_ID=] [MESSAGE=Method invoked ,METHOD_NAME=validateCallbackOverr
10:36:58 AM PIT >> FINE : MINION : ide,METHOD_PARAMETERS=callbackUrl:null,merchantCallbackUrl:https://mpass-v7-dev.us-east-2.elasticbeanstalk.com/callback]

10:36:58 AM PIT >> FINE : Coverage generator Minion exited ok
10:36:58 AM PIT >> INFO : Calculated coverage in 71 seconds.
Exception in thread "main" org.pitest.help.PitHelpError: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
See http://pitest.org for more details.
	at org.pitest.coverage.execute.DefaultCoverageGenerator.verifyBuildSuitableForMutationTesting(DefaultCoverageGenerator.java:109)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:94)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:49)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:116)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:49)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
:pitest FAILED
```
Is the test that is failing the last test that was examined `com.mastercard.srci.middleware.validator.MerchantCallbackUrlValidatorTest.positivePath_CallbackUrlIsNull_ShouldReturnMerchantCallbackUrl(...)` in this case OR are some other keyword I can search for?  The console output is over **8K** in length and I did not want to post it 😄 

I've tried commenting out the test that mentioned at the end of the console and it continues to fail which suggests to me that the failing test is earlier on but I can't immediately spot which test pitest is having trouble with
