### ISSUE TITLE
pitest couldn't run

### ISSUE THREAD

**Issue by orpoUser** [hcoles/pitest#254]
```
 [java] Please copy and paste the information and the complete stacktrace below when reporting an issue
 [java] VM : Java HotSpot(TM) 64-Bit Server VM
 [java] Vendor : Oracle Corporation
 [java] Version : 25.72-b15
 [java] Uptime : 88471
 [java] Input -> 
 [java]  1 : -Djava.io.tmpdir=**<omited>**
 [java]  2 : -Dbuild.sysclasspath=ignore
 [java]  3 : -Dant.home=ApacheAnt-1.9.x.0
 [java]  4 : -Dant.library.dir=ApacheAnt-1.9.x.0
 [java] BootClassPathSupported : true
 [java] 
 [java]     at org.pitest.mutationtest.tooling.JarCreatingJarFinder.classBytes(JarCreatingJarFinder.java:124)
 [java]     at org.pitest.mutationtest.tooling.JarCreatingJarFinder.addClass(JarCreatingJarFinder.java:113)
 [java]     at org.pitest.mutationtest.tooling.JarCreatingJarFinder.createJarFromClassPathResources(JarCreatingJarFinder.java:98)
 [java]     at org.pitest.mutationtest.tooling.JarCreatingJarFinder.createJar(JarCreatingJarFinder.java:74)
 [java]     at org.pitest.mutationtest.tooling.JarCreatingJarFinder.getJarLocation(JarCreatingJarFinder.java:63)
 [java]     at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:72)
 [java]     at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:45)
 [java]     at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:76)
 [java]     at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
 [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [java]     at java.lang.reflect.Method.invoke(Method.java:498)
 [java]     at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:217)
 [java]     at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:152)
 [java]     ... 20 more
 [java] Java Result: -1
```

**Comment by hcoles** [comment]
Could you please provide a bit more detail about your setup and ideally the relevant sections of your build script.

**Comment by orpoUser** [comment]
I'll try to upload as much as I can but it is going to be complicated without leaking details about how my current employer build systems.

I can tell you that we have a nice mix of byte instrumentation libraries (aspectj, spring load-time weaving) + lombok that might be getting into their way of pitest. What I was thinking is troubleshoot this locally using your source code and then I'll share the details of whatever I found.

BTW, Thanks for your quick reply!!!

**Comment by KyleRogers** [comment]
Maybe you can strip down your problem to a sample project that doesn't leak internals but might reproduce the problem? Without additional information what might cause this exception there is no way to find a problem.

**Comment by hcoles** [comment]
Closing as insufficient detail to reproduce.
