### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by xeland** [hcoles/pitest#266]
I have multi-project based on OSGi.
I build it through Gradle (with plugin biz.aQute.bnd.gradle:3.1.0)
for example:
  my.project1;
  my.project2;
  ...
  my.projectN.

Project "my.project1"  successfully passed the test with pitest.
I am getting the exception in project "my.project2", but I don't have any test in "my.project2".
(I deleted tests because I am getting the same exception with them)
(I deleted tests, but It did not help, the exception remains)

Log file:
```
...
...
:my.project2:compileJava UP-TO-DATE
:my.project2:processResources UP-TO-DATE
:my.project2:classes UP-TO-DATE
:my.project2:compileTestJava UP-TO-DATE
:my.project2:processTestResources UP-TO-DA
:my.project2:testClasses UP-TO-DATE
:my.project2:pitest
10:03:40 PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
        at org.pitest.reloc.asm.ClassReader.readLabel(Unknown Source)
        at org.pitest.reloc.asm.ClassReader.a(Unknown Source)
        at org.pitest.reloc.asm.ClassReader.a(Unknown Source)
        at org.pitest.reloc.asm.ClassReader.b(Unknown Source)
        at org.pitest.reloc.asm.ClassReader.accept(Unknown Source)
        at org.pitest.reloc.asm.ClassReader.accept(Unknown Source)
        at org.pitest.classinfo.ClassInfoVisitor.getClassInfo(ClassInfoVisitor.java:46)
        at org.pitest.classinfo.Repository.nameToClassInfo(Repository.java:70)
        at org.pitest.classinfo.Repository.fetchClass(Repository.java:60)
        at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:16)
        at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:6)
        at org.pitest.functional.FCollection.flatMapTo(FCollection.java:56)
        at org.pitest.functional.FCollection.flatMap(FCollection.java:66)
        at org.pitest.classpath.CodeSource.getCode(CodeSource.java:46)
        at org.pitest.mutationtest.verify.DefaultBuildVerifier.verify(DefaultBuildVerifier.java:32)
        at org.pitest.mutationtest.tooling.MutationCoverage.verifyBuildSuitableForMutationTesting(MutationCoverage.java:206)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:108)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:103)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:45)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:76)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
:my.project2:pitest FAILED

```

**Comment by hcoles** [comment]
Hi @xeland can you create a minimal project on github that re-creates the issue?

**Comment by xeland** [comment]
Thank you, but I can't re-create the issue, the project is too big.

**Comment by hcoles** [comment]
The usual process is to take the project where the issue was discovered and progressively remove source files, confirming that the issue can still be observed after each step.

Once a small project has been achieved the code can be modified to remove sensitive information.

The starting size of the project often does not have a large effect on how long this process takes.

Without a way to reproduce the issue it cannot be investigated.

**Comment by xeland** [comment]
I understand you.
But I can't simplify project it takes too much time.
Thank you for the answer.
