### ISSUE TITLE
problem after upgrade from 1.2.0 to 1.2.1: Tried to retrieve value but had None 

### ISSUE THREAD

**Issue by romani** [hcoles/pitest#367]
worked without problems on 1.2.0 version.

steps to reproduce:
```
$ git clone git@github.com:checkstyle/checkstyle.git
$ git checkout pitest-1.2.1
$ mvn -X -Ppitest-checkstyle-main,no-validations clean verify org.pitest:pitest-maven:mutationCoverage;
```

output:
```
6:40:30 AM PIT >> INFO : MINION : 6:40:30 AM PIT >> FINE : Gathering coverage for test Description [testClass=com.puppycrawl.tools.checkstyle.MainTest, name=com.puppycrawl.tools.checkstyle.MainTest]

6:40:34 AM PIT >> FINE : Coverage generator Minion exited ok
6:40:34 AM PIT >> INFO : Calculated coverage in 3 seconds.
6:40:34 AM PIT >> FINE : Used memory after coverage calculation 692 mb
6:40:34 AM PIT >> FINE : Free Memory after coverage calculation 614 mb
6:40:34 AM PIT >> WARNING : Found more than one mutation similar on same line in a finally block. Can't correct for inlining.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.369 s
[INFO] Finished at: 2017-07-06T06:40:34-07:00
[INFO] Final Memory: 90M/1333M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.2.1:mutationCoverage (default-cli) on project checkstyle: Execution default-cli of goal org.pitest:pitest-maven:1.2.1:mutationCoverage failed: Tried to retrieve value but had None. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.pitest:pitest-maven:1.2.1:mutationCoverage (default-cli) on project checkstyle: Execution default-cli of goal org.pitest:pitest-maven:1.2.1:mutationCoverage failed: Tried to retrieve value but had None.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.pitest:pitest-maven:1.2.1:mutationCoverage failed: Tried to retrieve value but had None.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.UnsupportedOperationException: Tried to retrieve value but had None.
	at org.pitest.functional.Option$None.value(Option.java:96)
	at org.pitest.classinfo.ComputeClassWriter.typeInfo(ComputeClassWriter.java:186)
	at org.pitest.classinfo.ComputeClassWriter.typeAncestors(ComputeClassWriter.java:142)
	at org.pitest.classinfo.ComputeClassWriter.getCommonSuperClass(ComputeClassWriter.java:94)
	at org.pitest.classinfo.ComputeClassWriter.getCommonSuperClass(ComputeClassWriter.java:72)
	at org.pitest.reloc.asm.ClassWriter.a(Unknown Source)
	at org.pitest.reloc.asm.Frame.a(Unknown Source)
	at org.pitest.reloc.asm.Frame.a(Unknown Source)
	at org.pitest.reloc.asm.MethodWriter.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.MethodVisitor.visitMaxs(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.a(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.b(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.accept(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.accept(Unknown Source)
	at org.pitest.mutationtest.engine.gregor.GregorMutater.getMutation(GregorMutater.java:108)
	at org.pitest.mutationtest.build.intercept.timeout.InfiniteLoopFilter.isInfiniteLoop(InfiniteLoopFilter.java:84)
	at org.pitest.mutationtest.build.intercept.timeout.InfiniteLoopFilter.findTimeoutMutants(InfiniteLoopFilter.java:75)
	at org.pitest.mutationtest.build.intercept.timeout.InfiniteLoopFilter.intercept(InfiniteLoopFilter.java:55)
	at org.pitest.mutationtest.build.CompoundMutationInterceptor.intercept(CompoundMutationInterceptor.java:38)
	at org.pitest.mutationtest.build.MutationSource.createMutations(MutationSource.java:68)
	at org.pitest.mutationtest.build.MutationTestBuilder$2.apply(MutationTestBuilder.java:100)
	at org.pitest.mutationtest.build.MutationTestBuilder$2.apply(MutationTestBuilder.java:97)
	at org.pitest.functional.FCollection.flatMapTo(FCollection.java:56)
	at org.pitest.functional.FCollection.flatMap(FCollection.java:66)
	at org.pitest.mutationtest.build.MutationTestBuilder.createMutationTestUnits(MutationTestBuilder.java:56)
	at org.pitest.mutationtest.tooling.MutationCoverage.buildMutationTests(MutationCoverage.java:279)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:132)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:114)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:48)
	at org.pitest.maven.RunPitStrategy.execute(RunPitStrategy.java:35)
	at org.pitest.maven.AbstractPitMojo.analyse(AbstractPitMojo.java:414)
	at org.pitest.maven.AbstractPitMojo.execute(AbstractPitMojo.java:358)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

**Comment by hcoles** [comment]
Looks as though the new static analysis checks are unable to resolve classes shipped in rt.jar such as java/lang/Exception.

I'm not too clear on why this would be an issue for checkstyle but not any of the example projects I run pitest across before release. Is there anything unusual in the checkstyle setup?

It should work if you disable the checks by passing -FINFIT and -FINFINC to the features list.

It would be simple enough to fallback to the classloader if the class isn't found on the supplied classpath, but I'd prefer to understand why this was necessary before doing so.

**Comment by hcoles** [comment]
Just pushed a fix, but not able to write an automated test as don't understand the root cause.

Will push out a release once the CI job completes in case this is a wider issue affecting other projects.

**Comment by hcoles** [comment]
1.2.2 is now released.
