### ISSUE TITLE
"Cannot allocate memory" in maven output but finally BUILD SUCCESS

### ISSUE THREAD

**Issue by romani** [hcoles/pitest#390]
I am not sure if this a problem or expected/possible behavior.
in output of maven execution we receive:
`
stderr  : Java HotSpot(TM) 64-Bit Server VM warning: stderr  : INFO: os::commit_memory(0x00000000cd100000, 70778880, 0) failed; error='Cannot allocate memory' (errno=12)
`

But build is Succesful at the end. So it could be possible that pitest is damaged code is such way to cause OOM error in jvm. 

I did not find any similar issue in web, so it will be good to receive clarification from authors on this.

full log (with `-Dverbose`) is at https://app.shippable.com/github/checkstyle/checkstyle/runs/4787/1/console 
```
7:20:26 AM PIT >> FINE : Running mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask, method=execute, methodDesc=()V], indexes=[145, 118], mutator=org.pitest.mutatiostderr  : ntest.engine.gregor.mutators.MathMutator], filename=CheckstyleAntTask.java, block=27, lineNumber=299, description=Replaced long subtraction with addition, testsInOrder=[com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testSetPropertiesNonExistingFstderr  : ile(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testNoConfigFile(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTeststderr  : .testNoFile(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testNonExistingConfig(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.Checkstystderr  : leAntTaskTest.testMaxErrors(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testDefaultFlawless(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstylstderr  : e.ant.CheckstyleAntTaskTest.testEmptyConfigFile(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testCustomRootModule(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppystderr  : crawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testMaxWarnings(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testOverrideProperty(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTasstderr  : kTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testPathsDirectoryWithNestedFile(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testFileSet(com.puppycrawl.tools.checksstderr  : tyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testPathsOneFile(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testSetPropertiesFile(com.puppstderr  : ycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testClassloaderInRootModule(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.stderr  : testCreateListenerExceptionWithXmlLogger(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testFailureProperty(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tostderr  : ols.checkstyle.ant.CheckstyleAntTaskTest.testXmlOutput(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testConfigurationByUrl(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), stderr  : com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testExecuteIgnoredModules(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testConfigurationByResource(com.puppycrawl.tools.checkstderr  : style.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testMaxWarningExceeded(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testDestroyed(com.puppystderr  : crawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testPathsFileWithLogVerification(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTstderr  : est.testCreateListenerException(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest.testCheckerException(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest), com.puppycrawl.tools.checstderr  : kstyle.ant.CheckstyleAntTaskTest.testExecuteLogOutput(com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTaskTest)], isInFinallyBlock=false, poison=NORMAL]
stderr  : 7:20:26 AM PIT >> FINE : mutating method execute
stderr  : 7:20:26 AM PIT >> FINE : 27 relevant test for execute
stderr  : 7:20:26 AM PIT >> FINE : replaced class with mutant in 211 ms
7:20:26 AM PIT >> FINE : Running 1 units
stderr  : Java HotSpot(TM) 64-Bit Server VM warning: stderr  : INFO: os::commit_memory(0x00000000cd100000, 70778880, 0) failed; error='Cannot allocate memory' (errno=12)
stdout  : #
# There is insufficient memory for the Java Runtime Environment to continue.
stdout  : # Native memory allocation (mmap) failed to map 70778880 bytes for committing reserved memory.
stdout  : # An error report file with more information is saved as:
# /root/src/github.com/checkstyle/checkstyle/hs_err_pid1048.log
7:22:26 AM PIT >> FINE : Exit code was - TIMEOUT
7:22:26 AM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
7:22:26 AM PIT >> FINE : Setting 1 unfinished runs to TIMED_OUT state
7:22:26 AM PIT >> FINE : Exit code was - TIMEOUT
7:22:26 AM PIT >> WARNING : Minion exited abnormally due to TIMED_OUT
7:22:26 AM PIT >> FINE : Setting 1 unfinished runs to TIMED_OUT state
7:22:26 AM PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.72-b15
Uptime : 420513
Input -> 
 1 : -Dclassworlds.conf=/usr/local/apache-maven-3.2.5/bin/m2.conf
 2 : -Dmaven.home=/usr/local/apache-maven-3.2.5
BootClassPathSupported : true

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
	at org.pitest.mutationtest.execute.MutationTestProcess.waitToDie(MutationTestProcess.java:47)
	at org.pitest.mutationtest.build.MutationTestUnit.waitForMinionToDie(MutationTestUnit.java:92)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestInSeperateProcessForMutationRange(MutationTestUnit.java:85)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestsInSeperateProcess(MutationTestUnit.java:68)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:55)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.72-b15
Uptime : 420513
Input -> 
 1 : -Dclassworlds.conf=/usr/local/apache-maven-3.2.5/bin/m2.conf
 2 : -Dmaven.home=/usr/local/apache-maven-3.2.5
BootClassPathSupported : true

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:65)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:65)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:37)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:63)
	... 5 more
7:22:26 AM PIT >> FINE : Exit code was - UNKNOWN_ERROR
7:22:26 AM PIT >> WARNING : Minion exited abnormally due to RUN_ERROR
7:22:26 AM PIT >> FINE : Setting 1 unfinished runs to RUN_ERROR state
7:22:26 AM PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.72-b15
Uptime : 420693
Input -> 
 1 : -Dclassworlds.conf=/usr/local/apache-maven-3.2.5/bin/m2.conf
 2 : -Dmaven.home=/usr/local/apache-maven-3.2.5
BootClassPathSupported : true

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
	at org.pitest.mutationtest.execute.MutationTestProcess.waitToDie(MutationTestProcess.java:47)
	at org.pitest.mutationtest.build.MutationTestUnit.waitForMinionToDie(MutationTestUnit.java:92)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestInSeperateProcessForMutationRange(MutationTestUnit.java:85)
	at org.pitest.mutationtest.build.MutationTestUnit.runTestsInSeperateProcess(MutationTestUnit.java:68)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:55)
	at org.pitest.mutationtest.build.MutationTestUnit.call(MutationTestUnit.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.72-b15
Uptime : 420693
Input -> 
 1 : -Dclassworlds.conf=/usr/local/apache-maven-3.2.5/bin/m2.conf
 2 : -Dmaven.home=/usr/local/apache-maven-3.2.5
BootClassPathSupported : true

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:65)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:65)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:37)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:63)
	... 5 more
7:22:26 AM PIT >> FINE : Exit code was - UNKNOWN_ERROR
7:22:26 AM PIT >> WARNING : Minion exited abnormally due to RUN_ERROR
7:22:26 AM PIT >> FINE : Setting 1 unfinished runs to RUN_ERROR state
```

**Comment by hcoles** [comment]
It looks like a mutation has caused a child jvm to run out of memory. Normally this would result in the mutant being marked with MEMORY_ERROR but it looks like the issue was severe enough to crash the JVM so it has been marked at a RUN_ERROR.

This is rare, but it is normal behaviour for pitest to continue. If you are only seeing 1 mutation causing a run error then there is probably nothing to worry about. If you are seeing lots of them then there might be a deeper problem.

**Comment by romani** [comment]
ok , lets close this issue for now and see how it will goes
