### ISSUE TITLE
JUnit 5 support

### ISSUE THREAD

**Issue by j-n-white** [hcoles/pitest#398]
I've been looking at JUnit 5 and I was hoping PIT could be configured to run those test. Unsurprisingly without any configuration PIT does not detect the JUnit 5 tests. I had hoped however that configuring a Junit 4 runner would work (http://junit.org/junit5/docs/5.0.0-M3/user-guide/#running-tests-junit-platform-runner) but this again does not detect the tests.

I also tried adding org.junit.vintage:junit-vintage-engine as a dependency but this resulted int the following error:
```
12:27:41 PIT >> INFO : MINION : 12:27:41 PIT >> FINE : Tests classes received

12:27:42 PIT >> FINE : MINION : org.pitest.util.PitError: JUnit Vintage

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.144-b01
Uptime : 763
Input ->
 1 : -ja
12:27:42 PIT >> FINE : MINION : vaagent:C:\Users\James\AppData\Local\Temp\1505820461095073950589561654995278462932241923747.jar
 2 : -Dclassworlds.conf=C:/Program Files/apache-maven/apache-maven-3.5.0/bin/m2.conf
 3 : -Dmaven.home=C:/Program Files/apache-maven/apache-maven-3.5.0
 4 : -Dm
12:27:42 PIT >> FINE : MINION : aven.multiModuleProjectDirectory=C:/Users/James/repo/mutationTestingDemo/java/MutationTestingDemo
BootClassPathSupported : true

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.util.IsolationUtils.convertForClass
12:27:42 PIT >> FINE : MINION : Loader(IsolationUtils.java:102)
        at org.pitest.junit.JUnitCustomRunnerTestUnitFinder.descriptionToTest(JUnitCustomRunnerTestUnitFinder.java:163)
        at org.pitest.junit.JUnitCustomRunnerTestUnitFinder.access$000(JUnitCustomRunnerTestUnitFinder.java:42)
        at
12:27:42 PIT >> FINE : MINION :  org.pitest.junit.JUnitCustomRunnerTestUnitFinder$1.apply(JUnitCustomRunnerTestUnitFinder.java:142)
        at org.pitest.junit.JUnitCustomRunnerTestUnitFinder$1.apply(JUnitCustomRunnerTestUnitFinder.java:138)
        at org.pitest.functional.FCollection.mapTo(FCollec
12:27:42 PIT >> FINE : MINION : tion.java:39)
        at org.pitest.functional.FCollection.map(FCollection.java:47)
        at org.pitest.functional.MutableList.map(MutableList.java:127)
        at org.pitest.junit.JUnitCustomRunnerTestUnitFinder.splitIntoFilteredUnits(JUnitCustomRunnerTestUnitFinder.java
12:27:42 PIT >> FINE : MINION : :132)
        at org.pitest.junit.JUnitCustomRunnerTestUnitFinder.findTestUnits(JUnitCustomRunnerTestUnitFinder.java:58)
        at org.pitest.junit.CompoundTestUnitFinder.findTestUnits(CompoundTestUnitFinder.java:20)
        at org.pitest.junit.CompoundTestUnitFinder.findT
12:27:42 PIT >> FINE : MINION : estUnits(CompoundTestUnitFinder.java:20)
        at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
        at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
        at org.pitest.testapi.execute.FindTestUnits.find
12:27:42 PIT >> FINE : MINION : TestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
        at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:163)
        at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:143)
        at org.pitest.coverag
12:27:42 PIT >> FINE : MINION : e.execute.CoverageMinion.main(CoverageMinion.java:85)
Caused by: java.lang.ClassNotFoundException: JUnit Vintage
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launc
12:27:42 PIT >> FINE : MINION : her$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.pitest.util.IsolationUtils.convertForClassLoader(I
12:27:42 PIT >> FINE : MINION : solationUtils.java:100)
        ... 17 more

12:27:42 PIT >> INFO : MINION : 12:27:42 PIT >> SEVERE : Error calculating coverage. Process will exit.
```

This is not a major issue as JUnit 5 is so new but it would be a nice enhancement for the future.

**Comment by damienbeaufils** [comment]
Thanks for this issue.
I have another example, using Gradle plugin:
```
$ ./gradlew pitest

> Task :pitest
Exception in thread "main" org.pitest.help.PitHelpError: No test library found on classpath. PIT requires either JUnit 4 (but can run JUnit 3 tests) or TestNG
See http://pitest.org for more details.
        at org.pitest.mutationtest.config.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:58)
        at org.pitest.mutationtest.config.LegacyTestFrameworkPlugin.createTestFrameworkConfiguration(LegacyTestFrameworkPlugin.java:38)
        at org.pitest.mutationtest.config.SettingsFactory.getTestFrameworkPlugin(SettingsFactory.java:131)
        at org.pitest.mutationtest.config.SettingsFactory.createCoverageOptions(SettingsFactory.java:140)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:91)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:48)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)


FAILURE: Build failed with an exception.
```

You can find a sample project to reproduce the issue [here](https://github.com/damienbeaufils/clean-architecture-demo/tree/junit5). Just checkout `junit5` branch and run `./gradlew pitest`.

Thanks.

**Comment by smoyer64** [comment]
Related to #284.

**Comment by Djaler** [comment]
What about this feature?

**Comment by hcoles** [comment]
Closing as JUnit 5 support is tracked on #284.
