### ISSUE TITLE
NPE when using goal org.pitest:pitest-maven:mutationCoverage

### ISSUE THREAD

**Issue by facanferff** [hcoles/pitest#435]
When using PIT with a jUnit test that deploys a Wildfly Swarm server that uses EJB and makes a HTTP request to an endpoint (given the service uses EJB) that attempts to create a MazeGetData (the only class I set in targetClasses), I get the following stacktrace (using the goal org.pitest:pitest-maven:mutationCoverage):

```
Caused by: java.lang.NullPointerException
        at sun.pitest.CodeCoverageStore.visitSingleProbe(CodeCoverageSto
2:43:33 PIT >> FINE : MINION : re.java:63)
        at rest.mazes.MazeGetData.<init>(MazeGetData.java:40)
        at rest.mazes.MazesApi.getMazes(MazesApi.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.j
2:43:33 PIT >> FINE : MINION : ava:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodI
2:43:33 PIT >> FINE : MINION : nterceptor.java:52)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
        at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
        at org.jboss.invocation.Int
2:43:33 PIT >> FINE : MINION : erceptorContext.proceed(InterceptorContext.java:340)
        at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
        at org.jboss.
2:43:33 PIT >> FINE : MINION : as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
        at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInte
2:43:33 PIT >> FINE : MINION : rceptor.java:21)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
        at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
        at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterc
2:43:33 PIT >> FINE : MINION : eptor.processInvocation(ComponentDispatcherInterceptor.java:52)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
        at org.jboss.as.ejb3.component.interceptors.NonPooledEJBComponentInstanceAssociatingInterceptor.processInvocat
2:43:33 PIT >> FINE : MINION : ion(NonPooledEJBComponentInstanceAssociatingInterceptor.java:59)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:275)
        ... 89 more
```

**Comment by facanferff** [comment]
To augment this, the code of MazeGetData is (line 40 is the first public MazeGetData()):

```
package rest.mazes;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import mazes.facade.tos.IMaze;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.ws.rs.core.UriInfo;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@ApiModel
public class MazeGetData {

	@XmlElement(name = "_links")
	@NotNull
	private MazeGetLinks links;
	
	@NotNull
	private int id;

	@NotNull
	@Min(3)
	@Max(50)
	@Pattern(regexp = "^[a-zA-Z0-9_ ]{3,50}$")
	private String name;

	@XmlElement(name = "_embedded")
	@JsonInclude(JsonInclude.Include.NON_NULL)
	private MazeGetDataEmbedded embedded;

	public MazeGetData() {

	}

	public MazeGetData(UriInfo uriInfo, IMaze maze) {
		this(uriInfo, maze, new MazeGetDataEmbedded(uriInfo, maze.getOrphanedRooms()));
	}

	public MazeGetData(UriInfo uriInfo, IMaze maze, MazeGetDataEmbedded embedded) {
		this.links = new MazeGetLinks(uriInfo, maze);
		this.id = maze.getId();
		this.name = maze.getName();
		this.embedded = embedded;
	}

	@ApiModelProperty(name = "_links")
	public MazeGetLinks getLinks() {
		return links;
	}

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	@JsonInclude(JsonInclude.Include.NON_NULL)
	public MazeGetDataEmbedded getEmbedded() {
		return embedded;
	}
}
```
