### ISSUE TITLE
IllegalArgumentException with no reason

### ISSUE THREAD

**Issue by rnveach** [hcoles/pitest#453]
I am trying to add pitest to my project. It is not maven so I am using the command line through a Main class inside the classpath of my project. My project is split into multiple projects because it is a web application so I am just starting off we it executing on a single class and test.
When running this, I get an IllegalArgumentException with no reason and the program just ends abruptly.

My main code.
`````
	public static void main(String[] arguments) throws Exception {
		final String baseLocation = getWorkingDirectory();

		MutationCoverageReport.main(new String[] {//
						"--reportDir",
						baseLocation + "\\caches",
						"--targetClasses",
						"com.company.area1.MyClass",
						"--targetTests",
						"com.company.area2.MyClassTest",
						"--sourceDirs",
						baseLocation
								+ "\\area1\\com\\company\\area1" });
	}

	private static String getWorkingDirectory() throws IOException {
		final File path = new File(".");
		final File directory = new File(path.getCanonicalPath());

		return directory.getParentFile().getCanonicalPath();
	}
`````

This is the output and full exception:
````
8:06:28 AM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
8:06:30 AM PIT >> INFO : Sending 1 test classes to minion
8:06:30 AM PIT >> INFO : Sent tests to minion
8:06:30 AM PIT >> INFO : MINION : 8:06:30 AM PIT >> INFO : Checking environment

8:06:30 AM PIT >> INFO : MINION : 8:06:30 AM PIT >> INFO : Found  1 tests

8:06:31 AM PIT >> INFO : MINION : 8:06:31 AM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

8:06:31 AM PIT >> INFO : MINION : 8:06:31 AM PIT >> INFO : 1 tests received

8:06:31 AM PIT >> INFO : MINION : 
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adap
8:06:31 AM PIT >> INFO : MINION : ter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:69)
	at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:50)
	at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:31)
	at org.pitest.testapi
8:06:31 AM PIT >> INFO : MINION : .execute.Pitest.executeTests(Pitest.java:57)
	at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
	at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:90)
8:06:31 AM PIT >> INFO : MINION : 
Caused by: java.lang.ClassNotFoundException: com.ibm.websphere.management.AdminServiceFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPr
8:06:31 AM PIT >> INFO : MINION : ivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(Class
8:06:31 AM PIT >> INFO : MINION : Loader.java:358)
	... 26 more

8:06:32 AM PIT >> INFO : MINION : log4j:WARN No appenders could be found for logger (hsqldb.db..ENGINE).
8:06:32 AM PIT >> INFO : MINION : 
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

8:06:35 AM PIT >> INFO : MINION : [main] INFO org.apache.tiles.servlet.context.ServletUtil - Publishing TilesContext for context: gov.ssa.websphere.test.structs.simulations.TestServletContext
8:06:35 AM PIT >> INFO : MINION : 

8:06:35 AM PIT >> INFO : MINION : [main] INFO org.apache.tiles.access.TilesAccess - Publishing TilesContext for context: org.apache.tiles.servlet.context.ServletTilesApplicationContext
8:06:35 AM PIT >> INFO : MINION : 

8:06:41 AM PIT >> INFO : MINION : 8:06:41 AM PIT >> WARNING : More threads at end of test (6) com.company.area2.MyClassTest than start. (5)

/8:06:42 AM PIT >> INFO : Calculated coverage in 12 seconds.
Exception in thread "main" java.lang.IllegalArgumentException
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.pitest.mutationtest.build.intercept.javafeatures.TryWithResourcesMethodVisitor.<init>(TryWithResourcesMethodVisitor.java:175)
	at org.pitest.mutationtest.build.intercept.javafeatures.TryWithResourcesFilter.checkMehod(TryWithResourcesFilter.java:35)
	at org.pitest.mutationtest.build.intercept.javafeatures.TryWithResourcesFilter.begin(TryWithResourcesFilter.java:30)
	at org.pitest.mutationtest.build.CompoundMutationInterceptor.begin(CompoundMutationInterceptor.java:29)
	at org.pitest.mutationtest.build.MutationSource.createMutations(MutationSource.java:63)
	at org.pitest.mutationtest.build.MutationTestBuilder$2.apply(MutationTestBuilder.java:100)
	at org.pitest.mutationtest.build.MutationTestBuilder$2.apply(MutationTestBuilder.java:97)
	at org.pitest.functional.FCollection.flatMapTo(FCollection.java:55)
	at org.pitest.functional.FCollection.flatMap(FCollection.java:65)
	at org.pitest.mutationtest.build.MutationTestBuilder.createMutationTestUnits(MutationTestBuilder.java:56)
	at org.pitest.mutationtest.tooling.MutationCoverage.buildMutationTests(MutationCoverage.java:280)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:135)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:116)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:49)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
	at com.company.area2.standalone.Pitest.main(Pitest.java:15)
````

The project is closed source, so I can't give the source code, but I will help out with snippets if you can give me more details on the issue.

**Comment by rnveach** [comment]
It turns out struts' own ASM jar was interferring with pitest. As soon as I changed the order of dependencies for pitest to got past that exception.
However it gave me a new exception `NoClassDefFoundError: org/apache/commons/codec/binary/Base64`. I included `commons-codec-1.9.jar` and pitest finally ran to completion.

> "--sourceDirs", baseLocation + "\\area1\\com\\company\\area1"

This actually has to be `baseLocation + "\\area1"`. pitest traverses the directories itself for the package.
