### ISSUE TITLE
Is Pitest compatible with Spek ?

### ISSUE THREAD

**Issue by laurentlr** [hcoles/pitest#455]
Hello,

I have some code in Java, and I test it with Spek in Kotlin.
But Pitest tells me there is No Coverage on all my code tested with Spek.

Since Pitest modify the code and run the tests again, it should be able to work with any kind of tests right ?

**Comment by hcoles** [comment]
Pitest has not been specifically tested with Spek, but in theory it should work out of the box if you are using it via JUnit and a RunWith annotation, or with the addition of the Junit5 plugin if you are not.

https://github.com/pitest/pitest-junit5-plugin

That said there could be issues as you might be the first person to try it.

**Comment by laurentlr** [comment]
I did a sample repo for an Android/Spek/Pitest project : https://github.com/laurentlr/PocAndroidPitest

I'm kind stuck, when I don't use the "@RunWith(JUnitPlatform::class)" annoation, the spek tests are not run with pitest. And when I use it, i got this issue : 

> 12:17:24 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.152-b16
Uptime : 1695
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true


Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.152-b16
Uptime : 1695
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:103)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:49)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:49)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.152-b16
Uptime : 1695
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:142)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:87)
        ... 6 more


FAILURE: Build failed with an exception.

**Comment by asm0dey** [comment]
I +1 this issue

**Comment by SkittishSloth** [comment]
+1 also. No coverage if I run KotlinTest also - trying out frameworks to find something more "kotlin-esque" than JUnit or TestNG. No luck yet.

**Comment by jayudey-wf** [comment]
One thing I've noticed that seems odd is that when `pitest` performs its initial test run the tests run and coverage information is collected but then it seems like on the subsequent 'mutation' killing test runs no tests are run
