### ISSUE TITLE
pitest 1.4.0 and junit 5.2.0: java.lang.NoClassDefFoundError: org/pitest/functional/Option

### ISSUE THREAD

**Issue by oneiros-de** [hcoles/pitest#465]
Running pitest 1.4.0 (gradle plugin is 1.3.0) with Junit 5.2.0 and Mockito 2.18.3 fails with

```
15:42:03 PIT >> FINE : MINION : java.lang.NoClassDefFoundError: org/pitest/functional/Option

15:42:03 PIT >> FINE : MINION :         at org.pitest.junit5.JUnit5TestPluginFactory.createTestFrameworkConfiguration(JUnit5TestPluginFactory.java:34)
15:42:03 PIT >> FINE : MINION : 

15:42:03 PIT >> FINE : MINION :         at org.pitest.mutationtest.config.MinionSettings.getTestFrameworkPlugin(MinionSettings.java:31)
15:42:03 PIT >> FINE : MINION : 

15:42:03 PIT >> FINE : MINION :         at org.pitest.coverage.execute.CoverageMinion.createTestPlugin(CoverageMinion.java:166)
15:42:03 PIT >> FINE : MINION : 

15:42:03 PIT >> FINE : MINION :         at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:135)
15:42:03 PIT >> FINE : MINION : 

15:42:03 PIT >> FINE : MINION :         at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:84)
15:42:03 PIT >> FINE : MINION : 

15:42:03 PIT >> FINE : MINION : Caused by: java.lang.ClassNotFoundException: org.pitest.functional.Option
15:42:03 PIT >> FINE : MINION : 
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
15:42:03 PIT >> FINE : MINION : 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

15:42:03 PIT >> FINE : MINION :         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
15:42:03 PIT >> FINE : MINION : 

15:42:03 PIT >> INFO : MINION : 15:42:03 PIT >> SEVERE : Error calculating coverage. Process will exit.
java.lang.NoClassDefFoundError: org/pitest/functional/Option
        at org.pitest.junit5.JUnit5TestPluginFactory.createTestFrameworkConfiguration(JUnit5TestPluginFactory.java:34)
        at org.pit
15:42:03 PIT >> INFO : MINION : est.mutationtest.config.MinionSettings.getTestFrameworkPlugin(MinionSettings.java:31)
        at org.pitest.coverage.execute.CoverageMinion.createTestPlugin(CoverageMinion.java:166)
        at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.
15:42:03 PIT >> INFO : MINION : java:135)
        at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:84)
Caused by: java.lang.ClassNotFoundException: org.pitest.functional.Option
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadCla
15:42:03 PIT >> INFO : MINION : ss(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

15:42:03 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.172-b11
Uptime : 701
Input -> 
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=DE
 3 : -Duser.language=de
 4 : -Duser.variant
BootClassPathSupported : true

```

I'll attach a complete output from gradle.

**Comment by hcoles** [comment]
Thanks for reporting - this is due to incompetence on my part - I forgot that the junit 5 plugin would need update for 1.4.0.

I'll push a release out shortly, after which the plugin can be moved into the main source tree (as it now builds on a minimum of java 8) so this sort of this shouldn't happen again.

**Comment by hcoles** [comment]
Version 0.5 of the junit 5 plugin is now syncing across to maven central.

**Comment by oneiros-de** [comment]
That gives a [different error](https://github.com/hcoles/pitest/files/1978905/pitest.txt) - it might be related to me using the Mockito extensions for Junit5, though.

**Comment by hcoles** [comment]
@oneiros-de If you can put together a minimal project that reproduces the issue I can take a look.
