### ISSUE TITLE
PIT crashes on Maven

### ISSUE THREAD

**Issue by xgillard** [hcoles/pitest#522]
# Problem description
I have configured my continuous integration system (I use circleci) to build test and mutation test my code after every `git push`. Since yesterday, it fails with the error detailed below. 

# Hypotheses / Additional info
* I suspect this error to be the exact same as the unresolved #107 (stacktrace looks roughly the same) but I cannot guarantee it given that I'm running on Maven and #107 uses ANT and given that version number probably don't match.
* I suspect the problem to be caused by a resource exhaustion: when performing the exact same build on my local machine (MacOS Sierra), PIT works like a charm. It takes about 30mn but completes w/o any problem. In addition, this suspicion is backed by the fact that the only major difference between the last build passing on circleci and the first failing one is the addition of a bunch of computationally intensive tests.

Anyhow, thanks for providing us with PIT, I'm loving it !

# Trace
```
7:21:11 AM PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 10.0.2+13-Debian-1
Uptime : 350090
Input -> 
 1 : -Xmx3200m
 2 : -Dclassworlds.conf=/opt/apache-maven/bin/m2.conf
 3 : -Dmaven.home=/opt/apache-maven
 4 : -Dlibrary.jansi.path=/opt/apache-maven/lib/jansi-native
 5 : -Dmaven.multiModuleProjectDirectory=/home/circleci/repo
BootClassPathSupported : false

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
	at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:133)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:87)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:49)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:117)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:49)
	at org.pitest.maven.RunPitStrategy.execute(RunPitStrategy.java:35)
	at org.pitest.maven.AbstractPitMojo.analyse(AbstractPitMojo.java:445)
	at org.pitest.maven.AbstractPitMojo.execute(AbstractPitMojo.java:386)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 10.0.2+13-Debian-1
Uptime : 350090
Input -> 
 1 : -Xmx3200m
 2 : -Dclassworlds.conf=/opt/apache-maven/bin/m2.conf
 3 : -Dmaven.home=/opt/apache-maven
 4 : -Dlibrary.jansi.path=/opt/apache-maven/lib/jansi-native
 5 : -Dmaven.multiModuleProjectDirectory=/home/circleci/repo
BootClassPathSupported : false

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.util.SafeDataInputStream.readLong(SafeDataInputStream.java:97)
	at org.pitest.coverage.execute.Receive.readProbeHit(Receive.java:83)
	at org.pitest.coverage.execute.Receive.handleTestEnd(Receive.java:75)
	at org.pitest.coverage.execute.Receive.apply(Receive.java:45)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:57)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:35)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
	at java.base/java.io.DataInputStream.readLong(DataInputStream.java:421)
	at org.pitest.util.SafeDataInputStream.readLong(SafeDataInputStream.java:95)
	... 8 more
```

**Comment by johnmarty3** [comment]
I am having what seems like a very similar error, also using Maven, so I just wanted to add another data point.
This is happening when run locally for me. Maven 3.6.0, Java 8. 

I am very new to submitting defects, so please let me know if I can provide any other helpful information.

```
8:00:15 AM PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.152-b16
Uptime : 40063
Input ->
 1 : -Xmx2048m
 2 : -Dclassworlds.conf=C:\snapshotviews\maven\apache-maven-3.6.0\bin\..\bin\m2.conf
 3 : -Dmaven.home=C:\snapshotviews\maven\apache-maven-3.6.0\bin\..
 4 : -Dlibrary.jansi.path=C:\snapshotviews\maven\apache-maven-3.6.0\bin\..\lib\jansi-native
 5 : -Dmaven.multiModuleProjectDirectory=C:\snapshotviews\git\rvs-service-container
 6 : -Djava.net.preferIPv4Stack=true
BootClassPathSupported : true

        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
        at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:138)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
        at org.pitest.maven.RunPitStrategy.execute(RunPitStrategy.java:35)
        at org.pitest.maven.AbstractPitMojo.analyse(AbstractPitMojo.java:463)
        at org.pitest.maven.AbstractPitMojo.execute(AbstractPitMojo.java:404)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.pitest.util.PitError: null

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.152-b16
Uptime : 40063
Input ->
 1 : -Xmx2048m
 2 : -Dclassworlds.conf=C:\snapshotviews\maven\apache-maven-3.6.0\bin\..\bin\m2.conf
 3 : -Dmaven.home=C:\snapshotviews\maven\apache-maven-3.6.0\bin\..
 4 : -Dlibrary.jansi.path=C:\snapshotviews\maven\apache-maven-3.6.0\bin\..\lib\jansi-native
 5 : -Dmaven.multiModuleProjectDirectory=C:\snapshotviews\git\rvs-service-container
 6 : -Djava.net.preferIPv4Stack=true
BootClassPathSupported : true

        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.util.SafeDataInputStream.read(SafeDataInputStream.java:65)
        at org.pitest.coverage.execute.Receive.handleTestEnd(Receive.java:69)
        at org.pitest.coverage.execute.Receive.apply(Receive.java:45)
        at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:57)
        at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:35)
        at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2675)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3150)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:859)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:355)
        at org.pitest.util.SafeDataInputStream.deserialize(SafeDataInputStream.java:105)
        at org.pitest.util.SafeDataInputStream.read(SafeDataInputStream.java:63)
        ... 7 more
```
