### ISSUE TITLE
StringIndexOutOfBoundsException while running pit

### ISSUE THREAD

**Issue by pedrorijo91** [hcoles/pitest#525]
Hey!

I'm running pitmp-maven-plugin version 1.3.6 (I know pitmp it's a different project, but this seems PIT specific), on a multi module maven project and I'm getting the following error when running `mvn pitmp:run`

```
8:05:07 PM PIT >> INFO : MINION : 8:05:07 PM PIT >> SEVERE : Error calculating coverage. Process will exit.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at org.pitest.junit.ParameterisedTestFilter.<init>(ParameterisedTestFilter.java:26)
	at org.pitest.junit.ParameterisedJUnitTestFinder.lambda$parameterizedToTestUnit$0(ParameterisedJUnitTestFinder.java:63)
	at org.pitest.functional.FCollection.mapTo(FCollection.java:42)
	at org.pitest.junit.ParameterisedJUnitTestFinder.handleParameterizedTest(ParameterisedJUnitTestFinder.java:55)
	at org.pitest.junit.ParameterisedJUnitTestFinder.findTestUnits(ParameterisedJUnitTestFinder.java:44)
	at org.pitest.junit.CompoundTestUnitFinder.findTestUnits(CompoundTestUnitFinder.java:20)
	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:157)
	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:138)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:84)
```

```
Coverage generation minion exited abnormally!
[ERROR]
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : Java HotSpot(TM) 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 25.144-b01
[ERROR] Uptime : 5914
[ERROR] Input ->
[ERROR]  1 : -Dapple.awt.UIElement=true
[ERROR]  2 : -Dclassworlds.conf=/usr/local/Cellar/maven/3.5.3/libexec/bin/m2.conf
[ERROR]  3 : -Dmaven.home=/usr/local/Cellar/maven/3.5.3/libexec
[ERROR]  4 : -Dlibrary.jansi.path=/usr/local/Cellar/maven/3.5.3/libexec/lib/jansi-native
[ERROR]  5 : -Dmaven.multiModuleProjectDirectory=/Users/pedro.rijo/repos/<REPO-NAME>
[ERROR] BootClassPathSupported : true
[ERROR]
````

if I try with `-X` flag, I get the following debug info:

```
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal eu.stamp-project:pitmp-maven-plugin:1.3.6:run failed: Coverage generation minion exited abnormally!
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!
    at org.pitest.util.Unchecked.translateCheckedException (Unchecked.java:20)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:103)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:49)
    at org.pitest.mutationtest.tooling.MutationCoverage.runReport (MutationCoverage.java:115)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:117)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:49)
    at eu.stamp_project.plugins.PmpProject.execute (PmpProject.java:184)
    at org.pitest.maven.PmpMojo.analyse (PmpMojo.java:312)
    at org.pitest.maven.AbstractPitMojo.execute (AbstractPitMojo.java:386)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!
    at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData (DefaultCoverageGenerator.java:142)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:87)
    at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage (DefaultCoverageGenerator.java:49)
    at org.pitest.mutationtest.tooling.MutationCoverage.runReport (MutationCoverage.java:115)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:117)
    at org.pitest.mutationtest.tooling.EntryPoint.execute (EntryPoint.java:49)
    at eu.stamp_project.plugins.PmpProject.execute (PmpProject.java:184)
    at org.pitest.maven.PmpMojo.analyse (PmpMojo.java:312)
    at org.pitest.maven.AbstractPitMojo.execute (AbstractPitMojo.java:386)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

not sure how to debug this or how to provide a reproducible example (it's a private company project). Do you have any hints that I can follow to provide you more exact information? Probably something related with parameterized tests (we do have a bunch) ?

btw, pitmp configuration:

```
            <plugin>
                <groupId>eu.stamp-project</groupId>
                <artifactId>pitmp-maven-plugin</artifactId>
                <version>1.3.6</version>
                <configuration>
                    <skippedModules>
                      <param>a-few-modules</param>
                    </skippedModules>
                    <mutateStaticInitializers>true</mutateStaticInitializers>
                    <mutators>
                        <mutator>ALL</mutator>
                    </mutators>
                    <excludedMethods>
                        <param>toString</param>
                        <param>toStringHelper</param>
                        <param>hashCode</param>
                        <param>equals</param>
                    </excludedMethods>
                    <mutationThreshold>1</mutationThreshold>
                    <targetDependencies>true</targetDependencies>
                    <withHistory>true</withHistory>
                    <threads>1</threads>
                </configuration>
            </plugin>
```

**Comment by pedrorijo91** [comment]
any clue on this @hcoles ?

**Comment by hcoles** [comment]
@pedrorijo91 If you can create a project that reproduced the issue I can take look. 

For a private repo the steps to do this are to keep removing things until you have the simplest thing that reproduces the issue, then replace any proprietary code with something you are happy to share.

**Comment by pedrorijo91** [comment]
will try to do it between tomorrow and saturday. just as a triage, is pitest tested against "normal" cases for junit parameterized tests?

**Comment by hcoles** [comment]
Yes it's tested against a few different parametrized test runners, I'd also expect that type of issue to manifest as an unexpectedly failing test rather than an error in gathering coverage (although I pitmp may somehow change this).

**Comment by pedrorijo91** [comment]
closing this issue as it seems due to a custom junit version.
