### ISSUE TITLE
'duplicate class definition for javassist.CtClassType' after indirect upgrade to Javassist 3.24.0-GA

### ISSUE THREAD

**Issue by Pr0methean** [hcoles/pitest#549]
I get the following error in Pitest 1.4.3 after upgrading Powermock from 2.0.0-beta5 to 2.0.0 and working around #548:
```
Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Versi
9:19:07 PM PIT >> INFO : MINION : on : 11.0.1+13-LTS
Uptime : 26093
Input -> 
 1 : -Djava.security.egd=file:/dev/./urandom
 2 : --add-opens=java.xml/jdk.xml.internal=ALL-UNNAMED
 3 : -javaagent:/tmp/15473279215440105529738281831882162887914457426756.jar
 4 : -Dclassworlds.conf=/usr/local/m
9:19:07 PM PIT >> INFO : MINION : aven-3.5.2/bin/m2.conf
 5 : -Dmaven.home=/usr/local/maven-3.5.2
 6 : -Dlibrary.jansi.path=/usr/local/maven-3.5.2/lib/jansi-native
 7 : -Dmaven.multiModuleProjectDirectory=/home/travis/build/Pr0methean/BetterRandom/betterrandom
BootClassPathSupported : fals
9:19:07 PM PIT >> INFO : MINION : e
	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:54)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:90)
Caused by: org.testng.TestN
9:19:07 PM PIT >> INFO : MINION : GException: 
An error occurred while instantiating class io.github.pr0methean.betterrandom.prng.Cmwc4096RandomTest: loader 'app' (instance of jdk.internal.loader.ClassLoaders$AppClassLoader) attempted duplicate class definition for javassist.CtClassType.
	
9:19:07 PM PIT >> INFO : MINION : at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:435)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
	at org.testng.internal.ClassImpl.get
9:19:07 PM PIT >> INFO : MINION : Instances(ClassImpl.java:190)
	at org.testng.TestClass.getInstances(TestClass.java:95)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:81)
	at org.testng.TestClass.init(TestClass.java:73)
	at org.testng.TestClass.<init>(TestClass.java:3
9:19:07 PM PIT >> INFO : MINION : 8)
	at org.testng.TestRunner.initMethods(TestRunner.java:389)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at org.testng.SuiteRunner$DefaultTe
9:19:07 PM PIT >> INFO : MINION : stRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRun
9:19:07 PM PIT >> INFO : MINION : ners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.pitest.testng.TestNGTestUnit.executeInCurrentLoader(TestNGTestUnit.java:88
9:19:07 PM PIT >> INFO : MINION : )
	at org.pitest.testng.TestNGTestUnit.execute(TestNGTestUnit.java:71)
	at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:50)
	at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:31)
	at org.pitest.te
9:19:07 PM PIT >> INFO : MINION : stapi.execute.Pitest.executeTests(Pitest.java:57)
	at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
	at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:51)
	... 1 more
Caused by: java.lang.LinkageError: loader 'app' (instance of 
9:19:07 PM PIT >> INFO : MINION : jdk.internal.loader.ClassLoaders$AppClassLoader) attempted duplicate class definition for javassist.CtClassType.
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java
9:19:07 PM PIT >> INFO : MINION : .base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Buil
9:19:07 PM PIT >> INFO : MINION : tinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLo
9:19:07 PM PIT >> INFO : MINION : aders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.powermock.core.classloader.javassist.ClassPoolFactory.create(ClassPoolFactory.java:33)
	at org.powermock.core.classloader.java
9:19:07 PM PIT >> INFO : MINION : ssist.JavassistMockClassLoader.<init>(JavassistMockClassLoader.java:55)
	at org.powermock.core.classloader.ByteCodeFramework$1.createClassloader(ByteCodeFramework.java:21)
	at org.powermock.core.classloader.MockClassLoaderBuilder.build(MockClassLoaderBuild
9:19:07 PM PIT >> INFO : MINION : er.java:58)
	at org.powermock.core.classloader.MockClassLoaderFactory.createMockClassLoader(MockClassLoaderFactory.java:141)
	at org.powermock.core.classloader.MockClassLoaderFactory.access$100(MockClassLoaderFactory.java:40)
	at org.powermock.core.classlo
9:19:07 PM PIT >> INFO : MINION : ader.MockClassLoaderFactory$1.run(MockClassLoaderFactory.java:126)
	at org.powermock.core.classloader.MockClassLoaderFactory$1.run(MockClassLoaderFactory.java:122)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.powermock.c
9:19:07 PM PIT >> INFO : MINION : ore.classloader.MockClassLoaderFactory.createWithPrivilegeAccessController(MockClassLoaderFactory.java:122)
	at org.powermock.core.classloader.MockClassLoaderFactory.createMockClassLoader(MockClassLoaderFactory.java:112)
	at org.powermock.core.classloader.
9:19:07 PM PIT >> INFO : MINION : MockClassLoaderFactory.create(MockClassLoaderFactory.java:93)
	at org.powermock.core.classloader.MockClassLoaderFactory.createForClass(MockClassLoaderFactory.java:68)
	at org.powermock.modules.testng.internal.TestNGMockClassLoaderFactory.createClassLoader(
9:19:07 PM PIT >> INFO : MINION : TestNGMockClassLoaderFactory.java:45)
	at org.powermock.modules.testng.internal.TestClassInstanceFactory.<init>(TestClassInstanceFactory.java:37)
	at org.powermock.modules.testng.internal.PowerMockClassloaderObjectFactory.newInstance(PowerMockClassloaderOb
9:19:07 PM PIT >> INFO : MINION : jectFactory.java:46)
	at org.powermock.modules.testng.PowerMockObjectFactory.newInstance(PowerMockObjectFactory.java:43)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:423)
	... 27 more
```

**Comment by Pr0methean** [comment]
Powermock 2.0.0 depends on org.javassist:javassist:jar:3.24.0-GA.

**Comment by Pr0methean** [comment]
A workaround is to add an explicit dependency on Javassist 3.22.0-CR1.

**Comment by Pr0methean** [comment]
3.23.1 produces a different error (note the ConcurrentModificationException root cause): https://travis-ci.org/Pr0methean/BetterRandom/jobs/481245818
