### ISSUE TITLE
ClassNotFoundException: org.pitest.mutationtest.config.PluginServices

### ISSUE THREAD

**Issue by bordozer** [hcoles/pitest#550]
Hi.
I'm trying to use your beautiful tool on my project. 
It's working perfect on my dev PC where mavenCentral() repository is accessible and enabled in gradle script (I use gradle 4.10.2).
But on other envs mavenCentral is closed. When I try to run pitest there I have an error

> Task :pitest FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: org/pitest/mutationtest/config/PluginServices
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:35)
Caused by: java.lang.ClassNotFoundException: org.pitest.mutationtest.config.PluginServices
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

I've tried add pitest-entry to the classpath but it does not help.
This sad fact is not aloud us to use pitest.. :(

Boris
bordozer@gmail.com

**Comment by buzzm** [comment]
You need to include all three of these jars from the command line:
java -cp pitest-1.4.7.jar:pitest-command-line-1.4.7.jar:pitest-entry-1.4.7.jar ...
