### ISSUE TITLE
pitest command line 1.4.6 No mutations found. This probably means there is an issue with either the supplied classpath or filters.

### ISSUE THREAD

**Issue by yuanxiaomama** [hcoles/pitest#586]
上午9:22:38 PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
上午9:22:39 PIT >> INFO : Sending 1 test classes to minion
上午9:22:39 PIT >> INFO : Sent tests to minion
上午9:22:39 PIT >> INFO : Calculated coverage in 0 seconds.
上午9:22:39 PIT >> INFO : Created  0 mutation test units
Exception in thread "main" org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
See http://pitest.org for more details.
        at org.pitest.mutationtest.tooling.MutationCoverage.checkMutationsFound(MutationCoverage.java:287)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:140)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)

java -cp /workspace/pitest-command-line-1.4.6.jar:/workspace/pitest-1.4.6.jar:/workspace/pitest-entry-1.4.6.jar:/workspace/junit-4.12.jar org.pitest.mutationtest.commandline.MutationCoverageReport --reportDir ./ --targetClasses com.controllers.TestController --targetTests com.toadtest.ToadClientTest --sourceDirs /workspace/test/src/main/java

**Comment by yuanxiaomama** [comment]
find the error

**Comment by caglarbilgin** [comment]
I have the same issue, any idea ?

**Comment by ianyong** [comment]
I resolved this issue by removing square brackets from my build path.
