### ISSUE TITLE
Error calculating coverage. Process will exit.

### ISSUE THREAD

**Issue by chaudharyakash** [hcoles/pitest#615]
1:30:32 PM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
1:30:33 PM PIT >> INFO : Sending 77 test classes to minion
1:30:33 PM PIT >> INFO : Sent tests to minion
1:30:33 PM PIT >> INFO : MINION : 1:30:33 PM PIT >> INFO : Checking environment

1:30:33 PM PIT >> INFO : MINION : 1:30:33 PM PIT >> SEVERE : Error calculating coverage. Process will exit.
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.refl
1:30:33 PM PIT >> INFO : MINION : ect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.re
1:30:33 PM PIT >> INFO : MINION : flect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationDa
1:30:33 PM PIT >> INFO : MINION : ta(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at org.pitest.junit.JUnit4SuiteFinder.apply(JUnit4SuiteFinder.java:30)
	at org.pitest.junit.JUnit4SuiteFinder.apply(JUnit4SuiteFinder.java:26)
	at org.pitest.extension.common.CompoundT
1:30:33 PM PIT >> INFO : MINION : estSuiteFinder.apply(CompoundTestSuiteFinder.java:20)
	at org.pitest.extension.common.CompoundTestSuiteFinder.apply(CompoundTestSuiteFinder.java:9)
	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:47)
	at org.pitest.testapi.exe
1:30:33 PM PIT >> INFO : MINION : cute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:157)
	at org.pite
1:30:33 PM PIT >> INFO : MINION : st.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:138)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:84)

1:30:33 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.144-b01
Uptime : 1218
Input -> 
BootClassPathSupported : true

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.144-b01
Uptime : 1219
Input -> 
BootClassPathSupported : true

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.144-b01
Uptime : 1218
Input -> 
BootClassPathSupported : true

	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:147)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
	... 6 more

**Comment by hcoles** [comment]
Thanks for the report. Can you confirm the version of pitest you are using and provide a minimal example project that reproduces the issue?

**Comment by chaudharyakash** [comment]
<dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-command-line</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-entry</artifactId>
            <version>1.4.7</version>
        </dependency>
        <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-ant</artifactId>
            <version>1.4.7</version>
        </dependency>

**Comment by chaudharyakash** [comment]
Creating a minimal project to reproduce the issue.

**Comment by hcoles** [comment]
Thanks @chaudharyakash, does this issue still occur with 1.4.8? (this release contained a fix for a bug in the coverage calculation).

**Comment by chaudharyakash** [comment]
let me try 1.4.8 version.
