### ISSUE TITLE
pitest + micronaut = null pointer exception

### ISSUE THREAD

**Issue by rmaclean-ee** [hcoles/pitest#620]
When using pitest with [micronaut](https://micronaut.io/), even the simplest scenario will fail with an NPE. Micronaut uses [annotation processors](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html) to augment code by doing [compile time changes](https://docs.micronaut.io/latest/guide/index.html#ioc) to the code, which is where the issue is triggered. 

For example, this class can be tested without issue:
```kotlin
class MathController {
    fun calc(
        a: Int,
        b: Int
    ): Int {
        return a+b
    }
}
```

However when we at [`@Validated`](https://docs.micronaut.io/latest/guide/index.html#validation) to the class, pitest will fail. 

Error from pitest:
```
5:09:26 PM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
5:09:27 PM PIT >> INFO : Sending 13 test classes to minion
5:09:27 PM PIT >> INFO : Sent tests to minion
5:09:27 PM PIT >> INFO : MINION : 5:09:27 PM PIT >> INFO : Checking environment

5:09:27 PM PIT >> INFO : MINION : 5:09:27 PM PIT >> INFO : Found  1 tests

5:09:27 PM PIT >> INFO : MINION : 5:09:27 PM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

5:09:27 PM PIT >> INFO : MINION : 5:09:27 PM PIT >> INFO : 1 tests received

/5:09:27 PM PIT >> INFO : Calculated coverage in 0 seconds.
Exception in thread "main" java.lang.NullPointerException
        at org.pitest.util.Preconditions.checkNotNull(Preconditions.java:6)
        at org.pitest.mutationtest.engine.MutationDetails.<init>(MutationDetails.java:54)
        at org.pitest.mutationtest.engine.gregor.MethodMutationContext.registerMutation(MethodMutationContext.java:35)
        at org.pitest.mutationtest.engine.gregor.AbstractInsnMutator.createMutationForInsnOpcode(AbstractInsnMutator.java:56)
        at org.pitest.mutationtest.engine.gregor.AbstractInsnMutator.visitInsn(AbstractInsnMutator.java:43)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.mutationtest.engine.gregor.AbstractInsnMutator.visitInsn(AbstractInsnMutator.java:45)
        at org.pitest.mutationtest.engine.gregor.AbstractInsnMutator.visitInsn(AbstractInsnMutator.java:45)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.mutationtest.engine.gregor.AvoidStringSwitchedMethodAdapter.visitInsn(AvoidStringSwitchedMethodAdapter.java:106)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.mutationtest.engine.gregor.blocks.BlockTrackingMethodDecorator.visitInsn(BlockTrackingMethodDecorator.java:45)
        at org.pitest.reloc.asm.MethodVisitor.visitInsn(MethodVisitor.java:313)
        at org.pitest.mutationtest.engine.gregor.analysis.InstructionTrackingMethodVisitor.visitInsn(InstructionTrackingMethodVisitor.java:28)
        at org.pitest.reloc.asm.ClassReader.readCode(ClassReader.java:1979)
        at org.pitest.reloc.asm.ClassReader.readMethod(ClassReader.java:1283)
        at org.pitest.reloc.asm.ClassReader.accept(ClassReader.java:688)
        at org.pitest.reloc.asm.ClassReader.accept(ClassReader.java:400)
        at org.pitest.mutationtest.engine.gregor.GregorMutater.findMutationsForBytes(GregorMutater.java:86)
        at org.pitest.mutationtest.engine.gregor.GregorMutater.lambda$findMutations$0(GregorMutater.java:75)
        at java.util.Optional.map(Optional.java:215)
        at org.pitest.mutationtest.engine.gregor.GregorMutater.findMutations(GregorMutater.java:68)
        at org.pitest.mutationtest.build.MutationSource.createMutations(MutationSource.java:55)
        at org.pitest.mutationtest.build.MutationTestBuilder.lambda$classToMutations$1(MutationTestBuilder.java:94)
        at org.pitest.functional.FCollection.flatMapTo(FCollection.java:58)
        at org.pitest.functional.FCollection.flatMap(FCollection.java:68)
        at org.pitest.mutationtest.build.MutationTestBuilder.createMutationTestUnits(MutationTestBuilder.java:58)
        at org.pitest.mutationtest.tooling.MutationCoverage.buildMutationTests(MutationCoverage.java:281)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:135)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
```

Reproducible sample code: https://github.com/rmaclean-ee/tmp-example-pitest-npe

**Comment by hcoles** [comment]
I looks like the annotation processor is not emitting the source file into the debug info of the compiled class. Pitest relies on this to map bytecode back to the file that generated it.

Is it possible to configure this in micronaut?

**Comment by rmaclean-ee** [comment]
No idea, my google-fu isn't finding it. I have [asked the Micronaut](https://stackoverflow.com/questions/56592911/is-there-a-config-to-include-source-files-in-the-debug-info) side to see if it can be done.

It sounds like a solution (or dead-end) so will close this and raise a new issue if I find a new problem when I am able to get the debug info correct.

**Comment by graemerocher** [comment]
@hcoles We currently generate byte code from your source files from the annotation processor. These are currently not mapped back to the emitting source since they are considered internal classes. What byte code entry are you expecting to expression this?

**Comment by hcoles** [comment]
Re-opened this as it looks like things can be fixed at the pitest end.

Micronaut looks to be generated a number of auxiliary classes based on the presence the Validated annotation. These are marked as synthetic (so pitest should ignore them), but unfortunately they will only filtered out after it has checked for the presence of the Filename attribute in the debug info.

I'll change pitest to allow for this to be null, so things will work with any annotation processor that does not set it (but does mark the files it generates as synthetic).

@graemerocher I think it would still be a good idea for the processor to add the debug Filename attribute. Being able to track back to which file caused classes to be emitted is likely to be useful for tools apart from pitest, and would be required if pitest were to support custom mutations for micronaut.

**Comment by rmaclean-ee** [comment]
> Generated 691 mutations Killed 181 (26%)

Was able to try out the new release today and all success 😄

**Comment by hcoles** [comment]
@rmaclean-ee I think there's still more to be done with micronaut, when I played with this locally pitest was generating a lot of what looked to be junk mutations in autogenerated code.

Not dug into it, but it seems that not everything micronaut is generating is marked as synthetic. Pitest may need to be updated to identify and filter out micronaut code.

**Comment by graemerocher** [comment]
@hcoles if you find something we are not marking as synthetic that sounds like a bug in the Micronaut side, please let us know and we can fix that.

**Comment by hcoles** [comment]
@graemerocher just taken a quick look and I think things are ok on the Micronaut side - all classes I've looked at so far are marked as synthetic.

Issue is that, for various reasons, pitest can't ignore all synthetic classes and Micronaut is slipping through that gap.
