### ISSUE TITLE
Breaks pitest-junit5-plugin 0.9

### ISSUE THREAD

**Issue by tmortagne** [hcoles/pitest#667]
When upgrading to pitest-maven 1.4.10 I get the following error:

```
2:43:15 PM PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.pitest.coverage.BlockLocation.<init>(Lorg/pitest/mutationtest/engine/Location;III)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
	at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:138)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.maven.RunPitStrategy.execute(RunPitStrategy.java:35)
	at org.pitest.maven.AbstractPitMojo.analyse(AbstractPitMojo.java:466)
	at org.pitest.maven.AbstractPitMojo.execute(AbstractPitMojo.java:407)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main(Maven35Launcher.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at jenkins.maven3.agent.Maven35Main.launch(Maven35Main.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.pitest.coverage.BlockLocation.<init>(Lorg/pitest/mutationtest/engine/Location;III)V
	at org.pitest.coverage.execute.Receive.handleProbes(Receive.java:64)
	at org.pitest.coverage.execute.Receive.apply(Receive.java:42)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:57)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:35)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 1 more
```

I also created an issue on pitest-junit5-plugin since I'm not sure where this should be fixed. See https://github.com/pitest/pitest-junit5-plugin/issues/34.

**Comment by hcoles** [comment]
@tmortagne From the stacktrace I think you may have an older version of pitest somehow included as a dependency in your project - the plugin runs fine with 1.4.10 on a small example project.

If this is not the case, could you post a minimal project that reproduces the issue?

**Comment by tmortagne** [comment]
OK I found what's wrong, we indeed end up with some of the pitest 1.4.7 modules because of the custom mutation engine we add as dependency to the plugin. Nothing to do with pitest-junit5-plugin.

Sorry for the noise and thanks for your pointer !
