### ISSUE TITLE
Surviving Mutant while actually three tests failed

### ISSUE THREAD

**Issue by Vampire** [hcoles/pitest#671]
I have a switch statement with 4 branches that is tested by 4 tests in 1 test class.
Now I have a survivor that should actually should have been killed.
The mutator is UOI4 and it mutated the switched on array field (an enum switch that was compiled to switching on the value of a lookup `int[]`).
When I copy this mutant to my built classes and run the tests, then three of the four tests are failing, that the third stays green is ok and expected.
The problem is, that it seems on this successful test is run, FINE logs say that only one test was found and executed and the mutant survived while it should have been killed properly. :-(
This is with latest 1.4.10.

**Comment by Vampire** [comment]
Ah, ok, the covering tests actually are the test classes, not the individual tests, so 1 covering test is actually correct.
But still it should have been killed.
I'm debugging a bit right now.
The tests are all four run, and strangely all actually succeed.
I could only imagine that the mutant was not actually used.

**Comment by Vampire** [comment]
Ok, I'm now at the `instrumentation.redefineClasses(definitions);` call in `org.pitest.boot.HotSwapAgent#hotSwap` that should load the mutant and the `byte[]` is the correct mutant, I dumped it to disk and looked inside. But nevertheless, the tests succeed while they shouldn't :-/

**Comment by Vampire** [comment]
This is really strange and I'm confused and concerned.
Do you have any hint on where I should look at next?

**Comment by Vampire** [comment]
This is really strange and I'm confused and concerned.
Do you have any hint on where I should look at next @hcoles?

**Comment by Vampire** [comment]
https://github.com/hengyunabc/dumpclass suggests that at the relevant time, the correct mutant is loaded

**Comment by hcoles** [comment]
If you can create a minimal project that recreates the issue I can take a look.

**Comment by Vampire** [comment]
Actually right now nothing works anymore, when trying to discover the coverage I get this:
```
RuntimeException while transforming  net/kautler/command/api/Command
java.lang.IllegalArgumentException
        at org.pitest.reloc.asm.ClassReader.readBootstrapMethodsAttribute(ClassReader.java:3265)
        at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:271)
        at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:176)
        at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:162)
        at org.pitest.coverage.CoverageTransformer.transformBytes(CoverageTransformer.java:48)
        at org.pitest.coverage.CoverageTransformer.transform(CoverageTransformer.java:35)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.pitest.classinfo.ClassName.lambda$nameToClass$1(ClassName.java:108)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:157)
        at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:138)
        at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:84)
20:25:42 PIT >> WARNING : Could not load net.kautler.command.api.CommandTest$1 Missing BootstrapMethods attribute in class file net/kautler/command/api/Command
RuntimeException while transforming  net/kautler/command/api/Command
java.lang.IllegalArgumentException
        at org.pitest.reloc.asm.ClassReader.readBootstrapMethodsAttribute(ClassReader.java:3265)
        at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:271)
        at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:176)
        at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:162)
        at org.pitest.coverage.CoverageTransformer.transformBytes(CoverageTransformer.java:48)
        at org.pitest.coverage.CoverageTransformer.transform(CoverageTransformer.java:35)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.pitest.classinfo.ClassName.lambda$nameToClass$1(ClassName.java:108)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:157)
        at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:138)
        at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:84)
20:25:42 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!
Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.131-b11
Uptime : 23096
Input ->
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=DE
 3 : -Duser.language=de
 4 : -Duser.variant
 5 : -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
BootClassPathSupported : true
Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.131-b11
Uptime : 23097
Input ->
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=DE
 3 : -Duser.language=de
 4 : -Duser.variant
 5 : -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
BootClassPathSupported : true
        at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!
Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.131-b11
Uptime : 23096
Input ->
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=DE
 3 : -Duser.language=de
 4 : -Duser.variant
 5 : -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
BootClassPathSupported : true
        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:147)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
        ... 6 more
```
:-/

**Comment by Vampire** [comment]
Ok, this latter proble was caused by #672 which includes the current working directory in the minion class path where I had a dumped `Command.class` lying around that ASM obviously didn't like.

**Comment by Vampire** [comment]
But during investigating this, I also found the problem I'm writing about here.

The problem is lack of or insufficient encapsulation.
If I only have the `UOI4` mutator, the mutant is killed.
If I only have the `UOI3` mutator, the mutant is killed.
If I have both, the `UOI3` and `UOI4` mutators, the second executed mutant survives, because the mutant causes static state to be modified.

Java byte code cannot really switch on enum values, only on integer values.
So what the compiler does is, it creates an anonymous inner class that has one switch map field.
This switch map field has generated integers at positions that are the ordinal values of the enum constants.

So in the byte code a

```java
switch (myEnum) {
    case CONSTANT_ONE: break;
    case CONSTANT_TWO: break;
    default: break;
```
actually looks like
```java
switch (MyClass$1.switchMapField[myEnum.ordinal()]) {
    case 1: break;
    case 2: break;
    default: break;
```
The mutators change this to `switch (--MyClass$1.switchMapField[myEnum.ordinal()]) {` or `switch (++MyClass$1.switchMapField[myEnum.ordinal()]) {`.
So the static state here is changed suddenly.
One mutator undoes the effect of the other one, but also causes the second one to survive.

So this actually is a false-negative.
The more important point is, this could as well easily produce false-positives, where mutations are seemingly killed, but the test only failed because some static state was changed due to the mutant.

**Comment by hcoles** [comment]
Static state and isolation is generally a tricky problem. It's possible to isolate each mutant completely by dropping the unit size down to 1, but performance suffers terribly as a jvm is then created per mutant.

There are some ideas I'd like to copy from the ruby system mutant which would allow corrupted state to be detected, but they would be a major change and I've not had chance to implement.

This instance is very interesting - I've not seen state introduced by the compiler before.

It should be possible to put a filter in place to prevent these mutations. 

Incidentally, unless you have a particular reason to do so I'd recommend not using the mutators in the rv package. They are there for researchers who want something that approximates the source level mutators from the literature, unlike the mutators in the default set that have been designed for day to day development. 

That said, your spate of recent bug reports has been very useful, this is probably the first scrutiny these operators have had.

**Comment by Vampire** [comment]
> Static state and isolation is generally a tricky problem. It's possible to isolate each mutant completely by dropping the unit size down to 1, but performance suffers terribly as a jvm is then created per mutant.
> 
> There are some ideas I'd like to copy from the ruby system mutant which would allow corrupted state to be detected, but they would be a major change and I've not had chance to implement.

Yeah, that's a problematic point of course.
Always hard to make a trade-off between performance and correctness.
This was just very confusing. :-D

> This instance is very interesting - I've not seen state introduced by the compiler before.

Also the only instant I'm aware of and also only since recently, since trying to get 100% coverage on a switch statement that has a branch for each enum-constant and an `AssertionError`-throwing default case.

> It should be possible to put a filter in place to prevent these mutations.

You mean on my side, or on PIT side?
On my side I currently added those two mutants to my filter already for now.

> Incidentally, unless you have a particular reason to do so I'd recommend not using the mutators in the rv package. They are there for researchers who want something that approximates the source level mutators from the literature, unlike the mutators in the default set that have been designed for day to day development.

Well, as I started to write tests for this project I just created and since I learned PIT from contributing to checkstyle just recently, I thought I right away make my tests PIT-secured too.

I thought the more, the better and started with all available mutators enabled to see how it is going.
Actually I already disabled again the ABS, all CRCR and all ROR mutators, as those treat booleans as integers and just produce too many non-sense mutations and the UOI1 and UOI2 mutators as they produce too many unkillable mutants like adding post-fix in-/decrements on the last (or actually only usage of a method parameter) which can never be killed.

So currently I run with all non-RV mutators and from the RV-set all AOR, AOD and OBBN mutators and UOI3 and UOI4, as from the description and from what I have seen so far those should be rather safe against bullshit mutants and actually helped me already to kill mutants I had not considered. 

So far I only manually excluded one `MemberVariableMutator` that removed assignment to a final field in a constructor which cannot happen in reality and cannot be killed, as the assignment was `null`, one `InlineConstantMutator` that increased array-size of an array given to `String.format` which cannot be killed as this simply works, and one `RemoveConditionalMutator_EQUAL_IF` that removes the outer `if` of a double-checked locking idiom that of course is effectless logic-wise but is just a performance optimisation. Besides the switch-field UOI3 and UOI4 mutants of course.

> That said, your spate of recent bug reports has been very useful, this is probably the first scrutiny these operators have had.

Well, just a very shallow scrutiny, as I very fast disabled the mutators I reported the issues against, mainly due to their bad boolean-behaviour. :-D
