### ISSUE TITLE
pitest 1.5.1: java.lang.IllegalArgumentException: Unsupported api 524288

### ISSUE THREAD

**Issue by rikumi** [hcoles/pitest#751]
Commit 297ed3b seems to have involved a compatibility issue with asm. The [documentation](https://asm.ow2.io/javadoc/org/objectweb/asm/MethodVisitor.html) points out that `MethodVisitor` only supports ASM4, ASM5, ASM6 and ASM7.

The stack trace:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported api 524288
        at org.objectweb.asm.MethodVisitor.<init>(MethodVisitor.java:84)
        at org.objectweb.asm.MethodVisitor.<init>(MethodVisitor.java:71)
        at org.pitest.mutationtest.build.intercept.javafeatures.TryWithResourcesMethodVisitor.<init>(TryWithResourcesMethodVisitor.java:176)
```

**Comment by hcoles** [comment]
Thanks @rikumi, can you provide a bit more detail about what triggers this error for you? (java version, preview features etc?).

**Comment by oorakci** [comment]
I encountered the same error. The dependency i added to pitest-maven plugin dependencies was causing this problem. Excluding asm dependency solved the problem.

```
<exclusion>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm</artifactId>
</exclusion>
```
