### ISSUE TITLE
Failure to run PITest

### ISSUE THREAD

**Issue by islamelgendy** [hcoles/pitest#783]
I tried running pitest for the first time on a project, so this might be a beginner mistake. I'm not sure where to start troubleshooting, though. The unusual part is that I was able to successfully run it before with an example, and I saw the generated reports. However, few days later I tried to run pitest on a different project and there was an error. I went back to the same example which was running before, and now it gives me the same error. 
Here's the output:

12:02:54 PIT >> INFO : Sending 1 test classes to slave
12:02:54 PIT >> INFO : Sent tests to slave
12:02:54 PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: org.pitest.util.PitError: Connection reset

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Private Build
Version : 25.252-b09
Uptime : 4716
Input -> 
 1 : -Dclassworlds.conf=/usr/share/maven/bin/m2.conf
 2 : -Dmaven.home=/usr/share/maven
 3 : -Dlibrary.jansi.path=/usr/share/maven/lib/jansi-native
 4 : -Dmaven.multiModuleProjectDirectory=/home/vaio/MyWork/Code/MutationTestingDemo
BootClassPathSupported : true

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:60)
	at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:131)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:85)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:49)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:112)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:101)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
	at org.pitest.maven.RunPitStrategy.execute(RunPitStrategy.java:32)
	at org.pitest.maven.PitMojo.analyse(PitMojo.java:361)
	at org.pitest.maven.PitMojo.execute(PitMojo.java:326)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.pitest.util.PitError: Connection reset

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Private Build
Version : 25.252-b09
Uptime : 4716
Input -> 
 1 : -Dclassworlds.conf=/usr/share/maven/bin/m2.conf
 2 : -Dmaven.home=/usr/share/maven
 3 : -Dlibrary.jansi.path=/usr/share/maven/lib/jansi-native
 4 : -Dmaven.multiModuleProjectDirectory=/home/vaio/MyWork/Code/MutationTestingDemo
BootClassPathSupported : true

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:65)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:63)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:36)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:63)
	... 5 more
12:02:54 PIT >> SEVERE : Coverage generator Slave exited abnormally due to UNKNOWN_ERROR
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.492 s
[INFO] Finished at: 2020-07-21T12:02:54+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.1.4:mutationCoverage (default-cli) on project MutationTestingDemo: Execution default-cli of goal org.pitest:pitest-maven:1.1.4:mutationCoverage failed: Coverage generation slave exited abnormally!
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : Private Build
[ERROR] Version : 25.252-b09
[ERROR] Uptime : 4721
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/usr/share/maven/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/usr/share/maven
[ERROR]  3 : -Dlibrary.jansi.path=/usr/share/maven/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/home/vaio/MyWork/Code/MutationTestingDemo
[ERROR] BootClassPathSupported : true
[ERROR] 
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : Private Build
[ERROR] Version : 25.252-b09
[ERROR] Uptime : 4721
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/usr/share/maven/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/usr/share/maven
[ERROR]  3 : -Dlibrary.jansi.path=/usr/share/maven/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/home/vaio/MyWork/Code/MutationTestingDemo
[ERROR] BootClassPathSupported : true
[ERROR]

**Comment by michielgkalkman** [comment]
Just curious ... do you use some kind of testrunner, like @RunWith(XYZRunner.class) ?

Might be that pitest has problems with that. 

Maybe you can share your code (on github e.g.)? That would make debugging and helping you easier.

**Comment by szpak** [comment]
Just to be sure (maybe versioning in Maven is different):
> Failed to execute goal org.pitest:pitest-maven:1.1.4:mutationCoverage

What version of PIT do you use? 1.1.4 (Jan 30, 2015) or some more modern (e.g. [1.5.2](https://github.com/hcoles/pitest/releases))?

**Comment by michielgkalkman** [comment]
O, that is an even better suggestion. I assumed the newest version was being used (why use an old version ?).
