### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space running against Kotlin project

### ISSUE THREAD

**Issue by JGulbronson** [hcoles/pitest#841]
Hello! I tried to run pitest against a Kotlin project, and it worked great for a small module. I tried on a larger one, and encountered the following error.

```
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 14.0.1+7
Uptime : 334777
Input ->
 1 : -Dfile.encoding=UTF-8
 2 : -Duser.country=CA
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : false

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:59)
        at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:138)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
        at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:121)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:51)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.TreeMap.put(TreeMap.java:575)
        at java.base/java.util.TreeSet.add(TreeSet.java:255)
        at org.pitest.coverage.CoverageData.addTestsToBlockMap(CoverageData.java:145)
        at org.pitest.coverage.CoverageData.calculateClassCoverage(CoverageData.java:134)
        at org.pitest.coverage.execute.DefaultCoverageGenerator$1.accept(DefaultCoverageGenerator.java:184)
        at org.pitest.coverage.execute.DefaultCoverageGenerator$1.accept(DefaultCoverageGenerator.java:176)
        at org.pitest.coverage.execute.Receive.handleTestEnd(Receive.java:78)
        at org.pitest.coverage.execute.Receive.apply(Receive.java:45)
        at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:56)
        at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:34)
        at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:11)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:832)
1:06:55 p.m. PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!
```

**Comment by StefanPenndorf** [comment]
Hi,

can you provide a link to the project or create a sample project? Without being able to reproduce it's very hard to find a solution...

**Comment by joel-costigliola** [comment]
Hi,

AssertJ is experiencing the same issue I believe when we check contributors PR test coverage, ex: https://github.com/assertj/assertj-core/runs/4335956195?check_suite_focus=true.

We experienced this issue for a while, the AssertJ codebase has expended a bit but I would think not significantly enough to run into a memory error. Being executed on github actions I'm not sure if we can specify to use more memory.

Here's some of the build logs interesting extract (after removing a bunch of  non printable characters):
```
4:31:25 PM PIT >> WARNING : Error while watching child process
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.pitest.util.CommunicationThread.waitToFinish(CommunicationThread.java:59)
	at org.pitest.coverage.execute.CoverageProcess.waitToDie(CoverageProcess.java:35)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:138)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:90)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:52)
	at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:149)
[INFO] ------------------------------------------------------------------------
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:139)
[INFO] BUILD FAILURE
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:123)
[INFO] ------------------------------------------------------------------------
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:54)
[INFO] Total time:  13:46 min
	at org.pitest.maven.RunPitStrategy.execute(RunPitStrategy.java:35)
[INFO] Finished at: 2021-11-26T16:31:25Z
	at org.pitest.maven.AbstractPitMojo.analyse(AbstractPitMojo.java:489)
[INFO] ------------------------------------------------------------------------
	at org.pitest.maven.AbstractPitMojo.execute(AbstractPitMojo.java:419)
Error:  Failed to execute goal org.pitest:pitest-maven:1.7.3:mutationCoverage (pitest) on project assertj-core: Execution pitest of goal org.pitest:pitest-maven:1.7.3:mutationCoverage failed: Coverage generation minion exited abnormally!
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.pitest.coverage.InstructionLocation.hashCode(InstructionLocation.java:36)
	at java.base/java.util.HashMap.hash(HashMap.java:340)
	at java.base/java.util.LinkedHashMap.get(LinkedHashMap.java:440)
	at org.pitest.coverage.CoverageData.addTestsToBlockMap(CoverageData.java:121)
	at org.pitest.coverage.CoverageData.calculateClassCoverage(CoverageData.java:71)
	at org.pitest.coverage.execute.DefaultCoverageGenerator$1.accept(DefaultCoverageGenerator.java:184)
	at org.pitest.coverage.execute.DefaultCoverageGenerator$1.accept(DefaultCoverageGenerator.java:176)
	at org.pitest.coverage.execute.Receive.handleTestEnd(Receive.java:76)
	at org.pitest.coverage.execute.Receive.apply(Receive.java:43)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:56)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:34)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
4:31:25 PM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
```
```

**Comment by hcoles** [comment]
Appologies for leaving this sitting here for so long. A fix should be in the 1.9.0 release.

**Comment by hcoles** [comment]
1.9.0 has now been released. It certainly improves things greatly for assertj. It would be good to know how well it addresses @JGulbronson original problem.

**Comment by joel-costigliola** [comment]
@hcoles I have re-enabled pitest on assertj-core pull requests, the OOM is gone but the build failed due to tests failing without mutation as per the logs of  https://github.com/assertj/assertj-core/runs/7315662523?check_suite_focus=true.

Here are the failing tests:
```
Description [testClass=org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver_JavaClassLibraryRecursionTest, name=[engine:junit-jupiter]/[class:org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver_JavaClassLibraryRecursionTest]/[method:should_assert_over_and_recurse_into_jcl_classes_when_configured_to_recurse_into_JCL()]]
Description [testClass=org.assertj.core.internal.DeepDifference_Test, name=[engine:junit-jupiter]/[class:org.assertj.core.internal.DeepDifference_Test]/[method:testBigDecimals()]]
Description [testClass=org.assertj.core.internal.DeepDifference_Test, name=[engine:junit-jupiter]/[class:org.assertj.core.internal.DeepDifference_Test]/[method:testUnorderedCollection()]]
Description [testClass=org.assertj.core.internal.DeepDifference_Test, name=[engine:junit-jupiter]/[class:org.assertj.core.internal.DeepDifference_Test]/[method:testEquivalentCollections()]]
Description [testClass=org.assertj.core.internal.DeepDifference_Test, name=[engine:junit-jupiter]/[class:org.assertj.core.internal.DeepDifference_Test]/[method:testSameObject()]]
```

This is unexpected to me as the tests run fine on a variety of environments (see the checks report on https://github.com/assertj/assertj-core/pull/2704) and locally for me, so I wonder if pitest does something special when running the tests without mutation.

I was actually able to reproduce the tests failure locally by running `mvn -e -B -Ppitest -Dfeatures="+GIT(from[HEAD~1]), +gitci" test` which is the command executed by our PR build. It executes with the following [profile](https://github.com/assertj/assertj-core/blob/main/pom.xml#L576):
```xml
    <profile>
      <id>pitest</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-maven</artifactId>
            <executions>
              <execution>
                <id>pitest</id>
                <phase>test-compile</phase>
                <goals>
                  <goal>mutationCoverage</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <!-- provides the pitest-git:aggregate goal to aggregate json files to be stored as artifact when accepting PRs from untrusted forks 
               refers to pitest-receive-pr.yml and pitest-updated-pr.yml for details.
          -->
          <plugin>
            <groupId>com.groupcdg</groupId>
            <artifactId>pitest-git-maven-plugin</artifactId>
            <version>${cdg.pitest.version}</version>
          </plugin>
        </plugins>
      </build>
    </profile>
``` 
I don't see any obvious configuration in this profile obvious that would lead to the tests failures, what these tests have in common is that they perform introspection (but they are not the only ones).

Do you want to follow up the discussion here or should I report a new issue?

**Comment by hcoles** [comment]
hi @joel-costigliola 

I think the issue is the custom argline. Pitest doesn't currently support the global maven argline property, so it needs to be duplicated in the pitest config.

```
          <jvmArgs>
            <value>-Dfile.encoding=${project.build.sourceEncoding}</value>
            <value>-Dnet.bytebuddy.experimental=true</value>
            <value>--add-opens=java.base/java.lang=ALL-UNNAMED</value>
            <value>--add-opens=java.base/java.math=ALL-UNNAMED</value>
            <value>--add-opens=java.base/java.util=ALL-UNNAMED</value>
            <value>--add-opens=java.base/sun.nio.fs=ALL-UNNAMED</value>
          </jvmArgs>
```

Pitest has all sorts of issues with arglines at the moment. I hoping to fix some of this in the next release.

By coincidence I was having a play with the assertj test suite yesterday. Everything was running green with this argline set (although my branch was a few commits behind).

**Comment by joel-costigliola** [comment]
Thanks for the quick reply, build succeeds now with the JVM args, looking forward to the next release.
