### ISSUE TITLE
Coverage generator Minion exited abnormally due to UNKNOWN_ERROR

### ISSUE THREAD

**Issue by ReturnHttp402** [hcoles/pitest#925]
```
❯ ant pit -Dprogram='mutant' -Dtest='BoundaryTests'
Buildfile: build.xml

test:
    [junit] Running BoundaryTests
    [junit] Tests run: 38, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec

pit:
   [pitest] 12:20:36 AM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
   [pitest] 12:20:36 AM PIT >> INFO : Incremental analysis reduced number of mutations by 0
   [pitest] 12:20:36 AM PIT >> INFO : Created  2 mutation test units in pre scan
   [pitest] 12:20:36 AM PIT >> INFO : Sending 0 test classes to minion
   [pitest] 12:20:36 AM PIT >> INFO : Sent tests to minion
   [pitest] 12:20:36 AM PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
   [pitest] Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally!
   [pitest] 
   [pitest] Please copy and paste the information and the complete stacktrace below when reporting an issue
   [pitest] VM : OpenJDK 64-Bit Server VM
   [pitest] Vendor : Homebrew
   [pitest] Version : 17+0
   [pitest] Uptime : 472
   [pitest] Input -> 
   [pitest] BootClassPathSupported : false
   [pitest] 
   [pitest] 
   [pitest] Please copy and paste the information and the complete stacktrace below when reporting an issue
   [pitest] VM : OpenJDK 64-Bit Server VM
   [pitest] Vendor : Homebrew
   [pitest] Version : 17+0
   [pitest] Uptime : 473
   [pitest] Input -> 
   [pitest] BootClassPathSupported : false
   [pitest] 
   [pitest]     at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
   [pitest]     at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:106)
   [pitest]     at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:52)
   [pitest]     at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:149)
   [pitest]     at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:139)
   [pitest]     at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:125)
   [pitest]     at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:52)
   [pitest]     at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
   [pitest]     at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
   [pitest] Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally!
   [pitest] 
   [pitest] Please copy and paste the information and the complete stacktrace below when reporting an issue
   [pitest] VM : OpenJDK 64-Bit Server VM
   [pitest] Vendor : Homebrew
   [pitest] Version : 17+0
   [pitest] Uptime : 472
   [pitest] Input -> 
   [pitest] BootClassPathSupported : false
   [pitest] 
   [pitest]     at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:149)
   [pitest]     at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:90)
   [pitest]     ... 7 more


```

Please help with this! Thanks!

**Comment by hcoles** [comment]
If you can create post a minimal (but complete) project that replicates the issue I can take a look.

**Comment by ReturnHttp402** [comment]
Hi @hcoles , thanks for the quick response, I've created a minimal project that can replicate the issue, please run:
` ant compile_orig` `ant compile_test` and then `ant pit` to reproduce the issue mentioned. Thanks.

**Comment by hcoles** [comment]
Thanks for the minimal project, it makes debugging these things *much* easier.

The problem looks to be the classpath supplied to the minion that runs the tests

```classPath="classes/"```

This includes only your own compiled code, without Junit (or any other library the code depends on). The minion is therefore erroring when it tries to load junit classes.

There's a (very old) working ant example here that shows one way to set the classpath up.

https://github.com/hcoles/pitest-ant-example/blob/master/build.xml

Unless you're really tied to ant for some reason, I'd suggest switching to maven or gradle. They make life much easier.

**Comment by ReturnHttp402** [comment]
Thank you! After adding junit jar file into test.path it is working, I will close this ticket.
