### ISSUE TITLE
"Coverage generation minion exited abnormally" with JUnit 5.8.0-RC1, not with M1

### ISSUE THREAD

**Issue by davidburstrom** [hcoles/pitest#926]
I've got a project (non-disclosable) using JUnit 5.8.0-M1, and when trying to bump to 5.8.0-RC1, the coverage minions fail. I've tested this on JDK 8, 11 and 15.

This is the difference in the `--classPath` (`<` is working, `>` is failing):

```
< /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.8.0-M1/ec6b09bebb1f08ab88ac3067e84a2c37abac0f47/junit-platform-engine-1.8.0-M1.jar
< /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.8.0-M1/606bc745051c0c2a608700d91a40d8a94698cdab/junit-platform-commons-1.8.0-M1.jar
< /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-engine/5.8.0-M1/7c9a3128baf19144a4dceb1d02e697384db8b2b4/junit-jupiter-engine-5.8.0-M1.jar
< /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.8.0-M1/6d6a0e5ee7373eaebba6a7357c36a468e490b47b/junit-jupiter-api-5.8.0-M1.jar
---
> /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.8.0-RC1/4b199e46e07d8952a45fea4467fe2db67dc5e361/junit-platform-engine-1.8.0-RC1.jar
> /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.8.0-RC1/c36e4083646b9d430f4b9d0f1a9deb12bba80093/junit-platform-commons-1.8.0-RC1.jar
> /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-engine/5.8.0-RC1/426e55d4724bff375f99e64dad52d6e37d58e2af/junit-jupiter-engine-5.8.0-RC1.jar
> /Users/user/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.8.0-RC1/6f4cde27132d619d459dd0d98a1f37b35f4b6b21/junit-jupiter-api-5.8.0-RC1.jar
56,58d55
< /Users/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.20/756521338269950c2a276f1abe6fef8e1a5e5528/kotlin-stdlib-jdk8-1.4.20.jar
< /Users/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.20/9de2c79e95d4b4699a455e88ba285a95352e0bea/kotlin-stdlib-jdk7-1.4.20.jar
< /Users/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.30-RC/dd23741884d3d030f21cc9db12936a2690b322e0/kotlin-stdlib-1.5.30-RC.jar
65d61
< /Users/user/.gradle/caches/modules-2/files-2.1/org.apiguardian/apiguardian-api/1.1.1/7ea550039f115fcc40990925490b8ebd4b93024a/apiguardian-api-1.1.1.jar
68,69d63
< /Users/user/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar
< /Users/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.30-RC/a85b7cb33ad571a90ba625845a9a554dae22ee33/kotlin-stdlib-common-1.5.30-RC.jar

Please let me know if I can provide more data.

**Comment by davidburstrom** [comment]
I found the issue.

Side note: Even with verbose logging, it wasn't reported to the main log Maybe because it's an exception that gets logged to stdout. I eventually managed to connect a debugger to the minion, which required patching the argument parser so that the `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5678"` commandline wasn't mangled (as the parser splits on `","`s).

The issue is that the `pitest-junit5-plugin` JAR bundles a version of 
`org.junit.platform.commons.util.AnnotationUtils` that is incompatible with what `org.junit.jupiter.engine.descriptor.DisplayNameUtils` from 5.8.0-RC1 needs.

Full stack trace:
```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:111)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.pitest.junit5.JUnit5TestUnitFinder.findTestUnits(JUnit5TestUnitFinder.java:79)
	at org.pitest.mutationtest.config.PrioritisingTestUnitFinder.findTestUnits(PrioritisingTestUnitFinder.java:19)
	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:57)
	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:155)
	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:136)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:83)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'test.Test'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	... 11 more
Caused by: java.lang.NoSuchMethodError: org.junit.platform.commons.util.AnnotationUtils.findAnnotation(Ljava/lang/Class;Ljava/lang/Class;Z)Ljava/util/Optional;
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.getDisplayNameGenerator(DisplayNameUtils.java:110)
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.lambda$createDisplayNameSupplierForClass$2(DisplayNameUtils.java:98)
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.determineDisplayName(DisplayNameUtils.java:88)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.<init>(JupiterTestDescriptor.java:69)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.<init>(ClassBasedTestDescriptor.java:96)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.<init>(ClassTestDescriptor.java:51)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.newClassTestDescriptor(ClassSelectorResolver.java:119)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$resolve$0(ClassSelectorResolver.java:71)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:246)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:209)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:71)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 16 more
```

**Comment by szpak** [comment]
Not related to the original problem, but:

> which required patching the argument parser so that the -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5678" commandline wasn't mangled (as the parser splits on ","s).

Unfortunately, it is a know problem: https://github.com/jopt-simple/jopt-simple/issues/147

**Comment by hcoles** [comment]
@davidburstrom Thanks for digging into this. It sounds like the simplest fix would be to wait for the release of 5.8.0 and build a new release against it. I don't think the plugin can avoid the hard dependency on the platform jars.

**Comment by davidburstrom** [comment]
You know best :) Out of curiosity, why does the plugin bundle classes from JUnit? Shouldn't they be provided on the test runtime classpath anyway?

**Comment by davidburstrom** [comment]
I've given the problem some thought over the weekend:

Maybe there is a good reason the JUnit classes are bundled, but _if_ there isn't, this is a suggestion to increase the range of compatible versions for a future pitest-junit5-plugin release:

* Set up a compatibility test suite that runs against different versions of JUnit 5 and different versions of Pitest.
* Set up source sets that compile against specific versions of Junit 5/Pitest and that implement a compatibility API defined by the plugin, e.g. `compatJU5Dot1` and `compatPT1DotX`.
* Select the proper source set through some means, e.g. by inspecting the classpath manifest files, reflection, ClassNotFoundExceptions, etc.

I know precisely how to achieve this in Gradle, but I'm not sure if Maven supports it nor, if it doesn't, if you'd like to switch build system in pitest-junit5-plugin for this reason.

**Comment by hcoles** [comment]
@davidburstrom 

A new release of the plugin has now been pushed out, built against JUnit Platform 1.8.0.

I've not had time to dig into what's happening on the classpath of the plugin, but agree that it ought to be possible to switch the scope of the platform dependency to 'provided' and pull the current version from the classpath. This may be trivially straight forward, or plagued with issues (as I said, I've not had chance to look). If you have time, I'd be more than happy to accept a pull request over at

https://github.com/pitest/pitest-junit5-plugin

Although it's possible that any implementation might spill over into this repo if it involves pulling classpath items from new locations.

**Comment by davidburstrom** [comment]
Thank you for the new release! I'm interested in making some improvements in pitest-junit5-plugin, but as I mentioned, since I'm fairly certain Maven doesn't support the test scenarios I'm thinking of, is it OK if I introduce Gradle as a build tool? It does not necessarily mean that the Maven build will be replaced, rather that I'd implement the scenarios where applicable and we can take it from there.

**Comment by CasperNLD** [comment]
Hi, 
I saw that this issue was still open and I was wondering if this problem is still present in version 1.9.10 or version 1.0.0 of pitest-junit5-plugin.
I am experiencing the same error.
Thanks in advance.

**Comment by hcoles** [comment]
@CasperNLD There are no known issues with the junit 5 plugin at the moment. Make sure your plugin version is compatible with your junit version.

From the plugin readme

* 1.1.0 requires pitest 1.9.0 or above and JUnit Platform 1.9.x (Jupiter 5.9.1)
* 1.0.0 requires pitest 1.9.0 or above and JUnit Platform 1.8.x (Jupiter 5.8.0)
